// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ovra/app/system/internal/dal/model"
)

func newFbAccountFlowRecord(db *gorm.DB, opts ...gen.DOOption) fbAccountFlowRecord {
	_fbAccountFlowRecord := fbAccountFlowRecord{}

	_fbAccountFlowRecord.fbAccountFlowRecordDo.UseDB(db, opts...)
	_fbAccountFlowRecord.fbAccountFlowRecordDo.UseModel(&model.FbAccountFlowRecord{})

	tableName := _fbAccountFlowRecord.fbAccountFlowRecordDo.TableName()
	_fbAccountFlowRecord.ALL = field.NewAsterisk(tableName)
	_fbAccountFlowRecord.ID = field.NewInt64(tableName, "id")
	_fbAccountFlowRecord.UserID = field.NewInt64(tableName, "user_id")
	_fbAccountFlowRecord.AccountType = field.NewString(tableName, "account_type")
	_fbAccountFlowRecord.FlowType = field.NewString(tableName, "flow_type")
	_fbAccountFlowRecord.BeforeAmount = field.NewFloat64(tableName, "before_amount")
	_fbAccountFlowRecord.FlowAmount = field.NewFloat64(tableName, "flow_amount")
	_fbAccountFlowRecord.AfterAmount = field.NewFloat64(tableName, "after_amount")
	_fbAccountFlowRecord.BusinessNo = field.NewString(tableName, "business_no")
	_fbAccountFlowRecord.Remark = field.NewString(tableName, "remark")
	_fbAccountFlowRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_fbAccountFlowRecord.WalletID = field.NewInt64(tableName, "wallet_id")
	_fbAccountFlowRecord.Currency = field.NewString(tableName, "currency")
	_fbAccountFlowRecord.Description = field.NewString(tableName, "description")
	_fbAccountFlowRecord.Status = field.NewString(tableName, "status")
	_fbAccountFlowRecord.UpdatedAt = field.NewTime(tableName, "updated_at")

	_fbAccountFlowRecord.fillFieldMap()

	return _fbAccountFlowRecord
}

// fbAccountFlowRecord 账户流水记录表
type fbAccountFlowRecord struct {
	fbAccountFlowRecordDo fbAccountFlowRecordDo

	ALL          field.Asterisk
	ID           field.Int64   // 记录ID
	UserID       field.Int64   // 用户ID
	AccountType  field.String  // 账户类型
	FlowType     field.String  // 交易类型
	BeforeAmount field.Float64 // 交易前余额
	FlowAmount   field.Float64 // 变动金额
	AfterAmount  field.Float64 // 交易后余额
	BusinessNo   field.String  // 业务编号
	Remark       field.String  // 备注
	CreatedAt    field.Time    // 创建时间
	WalletID     field.Int64   // 钱包ID
	Currency     field.String  // 货币单位
	Description  field.String  // 交易描述
	Status       field.String  // 交易状态
	UpdatedAt    field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (f fbAccountFlowRecord) Table(newTableName string) *fbAccountFlowRecord {
	f.fbAccountFlowRecordDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fbAccountFlowRecord) As(alias string) *fbAccountFlowRecord {
	f.fbAccountFlowRecordDo.DO = *(f.fbAccountFlowRecordDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fbAccountFlowRecord) updateTableName(table string) *fbAccountFlowRecord {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.UserID = field.NewInt64(table, "user_id")
	f.AccountType = field.NewString(table, "account_type")
	f.FlowType = field.NewString(table, "flow_type")
	f.BeforeAmount = field.NewFloat64(table, "before_amount")
	f.FlowAmount = field.NewFloat64(table, "flow_amount")
	f.AfterAmount = field.NewFloat64(table, "after_amount")
	f.BusinessNo = field.NewString(table, "business_no")
	f.Remark = field.NewString(table, "remark")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.WalletID = field.NewInt64(table, "wallet_id")
	f.Currency = field.NewString(table, "currency")
	f.Description = field.NewString(table, "description")
	f.Status = field.NewString(table, "status")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *fbAccountFlowRecord) WithContext(ctx context.Context) *fbAccountFlowRecordDo {
	return f.fbAccountFlowRecordDo.WithContext(ctx)
}

func (f fbAccountFlowRecord) TableName() string { return f.fbAccountFlowRecordDo.TableName() }

func (f fbAccountFlowRecord) Alias() string { return f.fbAccountFlowRecordDo.Alias() }

func (f fbAccountFlowRecord) Columns(cols ...field.Expr) gen.Columns {
	return f.fbAccountFlowRecordDo.Columns(cols...)
}

func (f *fbAccountFlowRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fbAccountFlowRecord) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 15)
	f.fieldMap["id"] = f.ID
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["account_type"] = f.AccountType
	f.fieldMap["flow_type"] = f.FlowType
	f.fieldMap["before_amount"] = f.BeforeAmount
	f.fieldMap["flow_amount"] = f.FlowAmount
	f.fieldMap["after_amount"] = f.AfterAmount
	f.fieldMap["business_no"] = f.BusinessNo
	f.fieldMap["remark"] = f.Remark
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["wallet_id"] = f.WalletID
	f.fieldMap["currency"] = f.Currency
	f.fieldMap["description"] = f.Description
	f.fieldMap["status"] = f.Status
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f fbAccountFlowRecord) clone(db *gorm.DB) fbAccountFlowRecord {
	f.fbAccountFlowRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fbAccountFlowRecord) replaceDB(db *gorm.DB) fbAccountFlowRecord {
	f.fbAccountFlowRecordDo.ReplaceDB(db)
	return f
}

type fbAccountFlowRecordDo struct{ gen.DO }

func (f fbAccountFlowRecordDo) Debug() *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Debug())
}

func (f fbAccountFlowRecordDo) WithContext(ctx context.Context) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fbAccountFlowRecordDo) ReadDB() *fbAccountFlowRecordDo {
	return f.Clauses(dbresolver.Read)
}

func (f fbAccountFlowRecordDo) WriteDB() *fbAccountFlowRecordDo {
	return f.Clauses(dbresolver.Write)
}

func (f fbAccountFlowRecordDo) Session(config *gorm.Session) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Session(config))
}

func (f fbAccountFlowRecordDo) Clauses(conds ...clause.Expression) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fbAccountFlowRecordDo) Returning(value interface{}, columns ...string) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fbAccountFlowRecordDo) Not(conds ...gen.Condition) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fbAccountFlowRecordDo) Or(conds ...gen.Condition) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fbAccountFlowRecordDo) Select(conds ...field.Expr) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fbAccountFlowRecordDo) Where(conds ...gen.Condition) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fbAccountFlowRecordDo) Order(conds ...field.Expr) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fbAccountFlowRecordDo) Distinct(cols ...field.Expr) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fbAccountFlowRecordDo) Omit(cols ...field.Expr) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fbAccountFlowRecordDo) Join(table schema.Tabler, on ...field.Expr) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fbAccountFlowRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fbAccountFlowRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fbAccountFlowRecordDo) Group(cols ...field.Expr) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fbAccountFlowRecordDo) Having(conds ...gen.Condition) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fbAccountFlowRecordDo) Limit(limit int) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fbAccountFlowRecordDo) Offset(offset int) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fbAccountFlowRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fbAccountFlowRecordDo) Unscoped() *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fbAccountFlowRecordDo) Create(values ...*model.FbAccountFlowRecord) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fbAccountFlowRecordDo) CreateInBatches(values []*model.FbAccountFlowRecord, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fbAccountFlowRecordDo) Save(values ...*model.FbAccountFlowRecord) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fbAccountFlowRecordDo) First() (*model.FbAccountFlowRecord, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbAccountFlowRecord), nil
	}
}

func (f fbAccountFlowRecordDo) Take() (*model.FbAccountFlowRecord, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbAccountFlowRecord), nil
	}
}

func (f fbAccountFlowRecordDo) Last() (*model.FbAccountFlowRecord, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbAccountFlowRecord), nil
	}
}

func (f fbAccountFlowRecordDo) Find() ([]*model.FbAccountFlowRecord, error) {
	result, err := f.DO.Find()
	return result.([]*model.FbAccountFlowRecord), err
}

func (f fbAccountFlowRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FbAccountFlowRecord, err error) {
	buf := make([]*model.FbAccountFlowRecord, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fbAccountFlowRecordDo) FindInBatches(result *[]*model.FbAccountFlowRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fbAccountFlowRecordDo) Attrs(attrs ...field.AssignExpr) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fbAccountFlowRecordDo) Assign(attrs ...field.AssignExpr) *fbAccountFlowRecordDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fbAccountFlowRecordDo) Joins(fields ...field.RelationField) *fbAccountFlowRecordDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fbAccountFlowRecordDo) Preload(fields ...field.RelationField) *fbAccountFlowRecordDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fbAccountFlowRecordDo) FirstOrInit() (*model.FbAccountFlowRecord, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbAccountFlowRecord), nil
	}
}

func (f fbAccountFlowRecordDo) FirstOrCreate() (*model.FbAccountFlowRecord, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbAccountFlowRecord), nil
	}
}

func (f fbAccountFlowRecordDo) FindByPage(offset int, limit int) (result []*model.FbAccountFlowRecord, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fbAccountFlowRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fbAccountFlowRecordDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fbAccountFlowRecordDo) Delete(models ...*model.FbAccountFlowRecord) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fbAccountFlowRecordDo) withDO(do gen.Dao) *fbAccountFlowRecordDo {
	f.DO = *do.(*gen.DO)
	return f
}
