// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ovra/app/system/internal/dal/model"
)

func newFbDeviceLoginLog(db *gorm.DB, opts ...gen.DOOption) fbDeviceLoginLog {
	_fbDeviceLoginLog := fbDeviceLoginLog{}

	_fbDeviceLoginLog.fbDeviceLoginLogDo.UseDB(db, opts...)
	_fbDeviceLoginLog.fbDeviceLoginLogDo.UseModel(&model.FbDeviceLoginLog{})

	tableName := _fbDeviceLoginLog.fbDeviceLoginLogDo.TableName()
	_fbDeviceLoginLog.ALL = field.NewAsterisk(tableName)
	_fbDeviceLoginLog.ID = field.NewInt64(tableName, "id")
	_fbDeviceLoginLog.UserID = field.NewInt64(tableName, "user_id")
	_fbDeviceLoginLog.DeviceID = field.NewString(tableName, "device_id")
	_fbDeviceLoginLog.LoginTime = field.NewTime(tableName, "login_time")
	_fbDeviceLoginLog.LoginIP = field.NewString(tableName, "login_ip")
	_fbDeviceLoginLog.LoginLocation = field.NewString(tableName, "login_location")
	_fbDeviceLoginLog.LoginType = field.NewString(tableName, "login_type")
	_fbDeviceLoginLog.LoginResult = field.NewString(tableName, "login_result")
	_fbDeviceLoginLog.FailReason = field.NewString(tableName, "fail_reason")
	_fbDeviceLoginLog.RiskLevel = field.NewString(tableName, "risk_level")
	_fbDeviceLoginLog.RiskDetail = field.NewString(tableName, "risk_detail")

	_fbDeviceLoginLog.fillFieldMap()

	return _fbDeviceLoginLog
}

// fbDeviceLoginLog 设备登录日志表
type fbDeviceLoginLog struct {
	fbDeviceLoginLogDo fbDeviceLoginLogDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键ID
	UserID        field.Int64  // 用户ID，0表示未登录用户
	DeviceID      field.String // 设备唯一标识
	LoginTime     field.Time   // 登录时间
	LoginIP       field.String // 登录IP
	LoginLocation field.String // 登录地点
	LoginType     field.String // 登录方式：PASSWORD/SMS/OTHER
	LoginResult   field.String // 登录结果：SUCCESS/FAIL
	FailReason    field.String // 失败原因
	RiskLevel     field.String // 风险等级：LOW/MEDIUM/HIGH
	RiskDetail    field.String // 风险详情

	fieldMap map[string]field.Expr
}

func (f fbDeviceLoginLog) Table(newTableName string) *fbDeviceLoginLog {
	f.fbDeviceLoginLogDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fbDeviceLoginLog) As(alias string) *fbDeviceLoginLog {
	f.fbDeviceLoginLogDo.DO = *(f.fbDeviceLoginLogDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fbDeviceLoginLog) updateTableName(table string) *fbDeviceLoginLog {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.UserID = field.NewInt64(table, "user_id")
	f.DeviceID = field.NewString(table, "device_id")
	f.LoginTime = field.NewTime(table, "login_time")
	f.LoginIP = field.NewString(table, "login_ip")
	f.LoginLocation = field.NewString(table, "login_location")
	f.LoginType = field.NewString(table, "login_type")
	f.LoginResult = field.NewString(table, "login_result")
	f.FailReason = field.NewString(table, "fail_reason")
	f.RiskLevel = field.NewString(table, "risk_level")
	f.RiskDetail = field.NewString(table, "risk_detail")

	f.fillFieldMap()

	return f
}

func (f *fbDeviceLoginLog) WithContext(ctx context.Context) *fbDeviceLoginLogDo {
	return f.fbDeviceLoginLogDo.WithContext(ctx)
}

func (f fbDeviceLoginLog) TableName() string { return f.fbDeviceLoginLogDo.TableName() }

func (f fbDeviceLoginLog) Alias() string { return f.fbDeviceLoginLogDo.Alias() }

func (f fbDeviceLoginLog) Columns(cols ...field.Expr) gen.Columns {
	return f.fbDeviceLoginLogDo.Columns(cols...)
}

func (f *fbDeviceLoginLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fbDeviceLoginLog) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 11)
	f.fieldMap["id"] = f.ID
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["device_id"] = f.DeviceID
	f.fieldMap["login_time"] = f.LoginTime
	f.fieldMap["login_ip"] = f.LoginIP
	f.fieldMap["login_location"] = f.LoginLocation
	f.fieldMap["login_type"] = f.LoginType
	f.fieldMap["login_result"] = f.LoginResult
	f.fieldMap["fail_reason"] = f.FailReason
	f.fieldMap["risk_level"] = f.RiskLevel
	f.fieldMap["risk_detail"] = f.RiskDetail
}

func (f fbDeviceLoginLog) clone(db *gorm.DB) fbDeviceLoginLog {
	f.fbDeviceLoginLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fbDeviceLoginLog) replaceDB(db *gorm.DB) fbDeviceLoginLog {
	f.fbDeviceLoginLogDo.ReplaceDB(db)
	return f
}

type fbDeviceLoginLogDo struct{ gen.DO }

func (f fbDeviceLoginLogDo) Debug() *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Debug())
}

func (f fbDeviceLoginLogDo) WithContext(ctx context.Context) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fbDeviceLoginLogDo) ReadDB() *fbDeviceLoginLogDo {
	return f.Clauses(dbresolver.Read)
}

func (f fbDeviceLoginLogDo) WriteDB() *fbDeviceLoginLogDo {
	return f.Clauses(dbresolver.Write)
}

func (f fbDeviceLoginLogDo) Session(config *gorm.Session) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Session(config))
}

func (f fbDeviceLoginLogDo) Clauses(conds ...clause.Expression) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fbDeviceLoginLogDo) Returning(value interface{}, columns ...string) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fbDeviceLoginLogDo) Not(conds ...gen.Condition) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fbDeviceLoginLogDo) Or(conds ...gen.Condition) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fbDeviceLoginLogDo) Select(conds ...field.Expr) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fbDeviceLoginLogDo) Where(conds ...gen.Condition) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fbDeviceLoginLogDo) Order(conds ...field.Expr) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fbDeviceLoginLogDo) Distinct(cols ...field.Expr) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fbDeviceLoginLogDo) Omit(cols ...field.Expr) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fbDeviceLoginLogDo) Join(table schema.Tabler, on ...field.Expr) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fbDeviceLoginLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fbDeviceLoginLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fbDeviceLoginLogDo) Group(cols ...field.Expr) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fbDeviceLoginLogDo) Having(conds ...gen.Condition) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fbDeviceLoginLogDo) Limit(limit int) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fbDeviceLoginLogDo) Offset(offset int) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fbDeviceLoginLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fbDeviceLoginLogDo) Unscoped() *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fbDeviceLoginLogDo) Create(values ...*model.FbDeviceLoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fbDeviceLoginLogDo) CreateInBatches(values []*model.FbDeviceLoginLog, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fbDeviceLoginLogDo) Save(values ...*model.FbDeviceLoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fbDeviceLoginLogDo) First() (*model.FbDeviceLoginLog, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbDeviceLoginLog), nil
	}
}

func (f fbDeviceLoginLogDo) Take() (*model.FbDeviceLoginLog, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbDeviceLoginLog), nil
	}
}

func (f fbDeviceLoginLogDo) Last() (*model.FbDeviceLoginLog, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbDeviceLoginLog), nil
	}
}

func (f fbDeviceLoginLogDo) Find() ([]*model.FbDeviceLoginLog, error) {
	result, err := f.DO.Find()
	return result.([]*model.FbDeviceLoginLog), err
}

func (f fbDeviceLoginLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FbDeviceLoginLog, err error) {
	buf := make([]*model.FbDeviceLoginLog, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fbDeviceLoginLogDo) FindInBatches(result *[]*model.FbDeviceLoginLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fbDeviceLoginLogDo) Attrs(attrs ...field.AssignExpr) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fbDeviceLoginLogDo) Assign(attrs ...field.AssignExpr) *fbDeviceLoginLogDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fbDeviceLoginLogDo) Joins(fields ...field.RelationField) *fbDeviceLoginLogDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fbDeviceLoginLogDo) Preload(fields ...field.RelationField) *fbDeviceLoginLogDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fbDeviceLoginLogDo) FirstOrInit() (*model.FbDeviceLoginLog, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbDeviceLoginLog), nil
	}
}

func (f fbDeviceLoginLogDo) FirstOrCreate() (*model.FbDeviceLoginLog, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbDeviceLoginLog), nil
	}
}

func (f fbDeviceLoginLogDo) FindByPage(offset int, limit int) (result []*model.FbDeviceLoginLog, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fbDeviceLoginLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fbDeviceLoginLogDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fbDeviceLoginLogDo) Delete(models ...*model.FbDeviceLoginLog) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fbDeviceLoginLogDo) withDO(do gen.Dao) *fbDeviceLoginLogDo {
	f.DO = *do.(*gen.DO)
	return f
}
