// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ovra/app/system/internal/dal/model"
)

func newFbDeposit(db *gorm.DB, opts ...gen.DOOption) fbDeposit {
	_fbDeposit := fbDeposit{}

	_fbDeposit.fbDepositDo.UseDB(db, opts...)
	_fbDeposit.fbDepositDo.UseModel(&model.FbDeposit{})

	tableName := _fbDeposit.fbDepositDo.TableName()
	_fbDeposit.ALL = field.NewAsterisk(tableName)
	_fbDeposit.ID = field.NewInt64(tableName, "id")
	_fbDeposit.UserID = field.NewInt64(tableName, "user_id")
	_fbDeposit.OrderNo = field.NewString(tableName, "order_no")
	_fbDeposit.Amount = field.NewFloat64(tableName, "amount")
	_fbDeposit.Status = field.NewString(tableName, "status")
	_fbDeposit.PaymentMethod = field.NewString(tableName, "payment_method")
	_fbDeposit.PaymentStatus = field.NewString(tableName, "payment_status")
	_fbDeposit.PaymentNo = field.NewString(tableName, "payment_no")
	_fbDeposit.PaymentTime = field.NewTime(tableName, "payment_time")
	_fbDeposit.Remark = field.NewString(tableName, "remark")
	_fbDeposit.Currency = field.NewString(tableName, "currency")
	_fbDeposit.TargetAccount = field.NewString(tableName, "target_account")
	_fbDeposit.Screenshot = field.NewString(tableName, "screenshot")
	_fbDeposit.CreatedAt = field.NewTime(tableName, "created_at")
	_fbDeposit.UpdatedAt = field.NewTime(tableName, "updated_at")

	_fbDeposit.fillFieldMap()

	return _fbDeposit
}

// fbDeposit 充值记录表
type fbDeposit struct {
	fbDepositDo fbDepositDo

	ALL           field.Asterisk
	ID            field.Int64
	UserID        field.Int64   // 用户ID
	OrderNo       field.String  // 订单号
	Amount        field.Float64 // 充值金额
	Status        field.String  // 状态
	PaymentMethod field.String  // 支付方式
	PaymentStatus field.String  // 支付状态
	PaymentNo     field.String  // 第三方支付单号
	PaymentTime   field.Time    // 支付时间
	Remark        field.String  // 备注
	Currency      field.String  // 货币类型(CNY或USDT)
	TargetAccount field.String  // 目标账户类型(MAIN普通钱包或FOREX外汇账户)
	Screenshot    field.String  // 充值截图文件路径或ID
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (f fbDeposit) Table(newTableName string) *fbDeposit {
	f.fbDepositDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fbDeposit) As(alias string) *fbDeposit {
	f.fbDepositDo.DO = *(f.fbDepositDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fbDeposit) updateTableName(table string) *fbDeposit {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.UserID = field.NewInt64(table, "user_id")
	f.OrderNo = field.NewString(table, "order_no")
	f.Amount = field.NewFloat64(table, "amount")
	f.Status = field.NewString(table, "status")
	f.PaymentMethod = field.NewString(table, "payment_method")
	f.PaymentStatus = field.NewString(table, "payment_status")
	f.PaymentNo = field.NewString(table, "payment_no")
	f.PaymentTime = field.NewTime(table, "payment_time")
	f.Remark = field.NewString(table, "remark")
	f.Currency = field.NewString(table, "currency")
	f.TargetAccount = field.NewString(table, "target_account")
	f.Screenshot = field.NewString(table, "screenshot")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *fbDeposit) WithContext(ctx context.Context) *fbDepositDo {
	return f.fbDepositDo.WithContext(ctx)
}

func (f fbDeposit) TableName() string { return f.fbDepositDo.TableName() }

func (f fbDeposit) Alias() string { return f.fbDepositDo.Alias() }

func (f fbDeposit) Columns(cols ...field.Expr) gen.Columns { return f.fbDepositDo.Columns(cols...) }

func (f *fbDeposit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fbDeposit) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 15)
	f.fieldMap["id"] = f.ID
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["order_no"] = f.OrderNo
	f.fieldMap["amount"] = f.Amount
	f.fieldMap["status"] = f.Status
	f.fieldMap["payment_method"] = f.PaymentMethod
	f.fieldMap["payment_status"] = f.PaymentStatus
	f.fieldMap["payment_no"] = f.PaymentNo
	f.fieldMap["payment_time"] = f.PaymentTime
	f.fieldMap["remark"] = f.Remark
	f.fieldMap["currency"] = f.Currency
	f.fieldMap["target_account"] = f.TargetAccount
	f.fieldMap["screenshot"] = f.Screenshot
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f fbDeposit) clone(db *gorm.DB) fbDeposit {
	f.fbDepositDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fbDeposit) replaceDB(db *gorm.DB) fbDeposit {
	f.fbDepositDo.ReplaceDB(db)
	return f
}

type fbDepositDo struct{ gen.DO }

func (f fbDepositDo) Debug() *fbDepositDo {
	return f.withDO(f.DO.Debug())
}

func (f fbDepositDo) WithContext(ctx context.Context) *fbDepositDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fbDepositDo) ReadDB() *fbDepositDo {
	return f.Clauses(dbresolver.Read)
}

func (f fbDepositDo) WriteDB() *fbDepositDo {
	return f.Clauses(dbresolver.Write)
}

func (f fbDepositDo) Session(config *gorm.Session) *fbDepositDo {
	return f.withDO(f.DO.Session(config))
}

func (f fbDepositDo) Clauses(conds ...clause.Expression) *fbDepositDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fbDepositDo) Returning(value interface{}, columns ...string) *fbDepositDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fbDepositDo) Not(conds ...gen.Condition) *fbDepositDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fbDepositDo) Or(conds ...gen.Condition) *fbDepositDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fbDepositDo) Select(conds ...field.Expr) *fbDepositDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fbDepositDo) Where(conds ...gen.Condition) *fbDepositDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fbDepositDo) Order(conds ...field.Expr) *fbDepositDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fbDepositDo) Distinct(cols ...field.Expr) *fbDepositDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fbDepositDo) Omit(cols ...field.Expr) *fbDepositDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fbDepositDo) Join(table schema.Tabler, on ...field.Expr) *fbDepositDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fbDepositDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fbDepositDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fbDepositDo) RightJoin(table schema.Tabler, on ...field.Expr) *fbDepositDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fbDepositDo) Group(cols ...field.Expr) *fbDepositDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fbDepositDo) Having(conds ...gen.Condition) *fbDepositDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fbDepositDo) Limit(limit int) *fbDepositDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fbDepositDo) Offset(offset int) *fbDepositDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fbDepositDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fbDepositDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fbDepositDo) Unscoped() *fbDepositDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fbDepositDo) Create(values ...*model.FbDeposit) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fbDepositDo) CreateInBatches(values []*model.FbDeposit, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fbDepositDo) Save(values ...*model.FbDeposit) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fbDepositDo) First() (*model.FbDeposit, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbDeposit), nil
	}
}

func (f fbDepositDo) Take() (*model.FbDeposit, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbDeposit), nil
	}
}

func (f fbDepositDo) Last() (*model.FbDeposit, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbDeposit), nil
	}
}

func (f fbDepositDo) Find() ([]*model.FbDeposit, error) {
	result, err := f.DO.Find()
	return result.([]*model.FbDeposit), err
}

func (f fbDepositDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FbDeposit, err error) {
	buf := make([]*model.FbDeposit, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fbDepositDo) FindInBatches(result *[]*model.FbDeposit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fbDepositDo) Attrs(attrs ...field.AssignExpr) *fbDepositDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fbDepositDo) Assign(attrs ...field.AssignExpr) *fbDepositDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fbDepositDo) Joins(fields ...field.RelationField) *fbDepositDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fbDepositDo) Preload(fields ...field.RelationField) *fbDepositDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fbDepositDo) FirstOrInit() (*model.FbDeposit, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbDeposit), nil
	}
}

func (f fbDepositDo) FirstOrCreate() (*model.FbDeposit, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbDeposit), nil
	}
}

func (f fbDepositDo) FindByPage(offset int, limit int) (result []*model.FbDeposit, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fbDepositDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fbDepositDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fbDepositDo) Delete(models ...*model.FbDeposit) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fbDepositDo) withDO(do gen.Dao) *fbDepositDo {
	f.DO = *do.(*gen.DO)
	return f
}
