// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ovra/app/system/internal/dal/model"
)

func newFbFundPosition(db *gorm.DB, opts ...gen.DOOption) fbFundPosition {
	_fbFundPosition := fbFundPosition{}

	_fbFundPosition.fbFundPositionDo.UseDB(db, opts...)
	_fbFundPosition.fbFundPositionDo.UseModel(&model.FbFundPosition{})

	tableName := _fbFundPosition.fbFundPositionDo.TableName()
	_fbFundPosition.ALL = field.NewAsterisk(tableName)
	_fbFundPosition.ID = field.NewInt64(tableName, "id")
	_fbFundPosition.UserID = field.NewInt64(tableName, "user_id")
	_fbFundPosition.FundCode = field.NewString(tableName, "fund_code")
	_fbFundPosition.Amount = field.NewFloat64(tableName, "amount")
	_fbFundPosition.BuyDate = field.NewTime(tableName, "buy_date")
	_fbFundPosition.StartDate = field.NewTime(tableName, "start_date")
	_fbFundPosition.EndDate = field.NewTime(tableName, "end_date")
	_fbFundPosition.Period = field.NewInt32(tableName, "period")
	_fbFundPosition.Rate = field.NewFloat64(tableName, "rate")
	_fbFundPosition.Profit = field.NewFloat64(tableName, "profit")
	_fbFundPosition.State = field.NewString(tableName, "state")
	_fbFundPosition.Status = field.NewBool(tableName, "status")
	_fbFundPosition.CreateTime = field.NewTime(tableName, "create_time")
	_fbFundPosition.UpdateTime = field.NewTime(tableName, "update_time")
	_fbFundPosition.LastProfitDate = field.NewTime(tableName, "last_profit_date")

	_fbFundPosition.fillFieldMap()

	return _fbFundPosition
}

// fbFundPosition 基金用户持仓表
type fbFundPosition struct {
	fbFundPositionDo fbFundPositionDo

	ALL            field.Asterisk
	ID             field.Int64
	UserID         field.Int64
	FundCode       field.String  // 基金代码
	Amount         field.Float64 // 投入持仓金额
	BuyDate        field.Time    // 买入日期
	StartDate      field.Time    // 开始计息日
	EndDate        field.Time    // 到期日
	Period         field.Int32   // 投资周期(天)
	Rate           field.Float64 // 收益率
	Profit         field.Float64 // 每天收益(预估)
	State          field.String  // 进行中-ONGOING, 未投入-NONE
	Status         field.Bool    // 状态：0-结束，1-进行中
	CreateTime     field.Time
	UpdateTime     field.Time
	LastProfitDate field.Time // 该持仓最后一次收益计算日期(冗余字段)

	fieldMap map[string]field.Expr
}

func (f fbFundPosition) Table(newTableName string) *fbFundPosition {
	f.fbFundPositionDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fbFundPosition) As(alias string) *fbFundPosition {
	f.fbFundPositionDo.DO = *(f.fbFundPositionDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fbFundPosition) updateTableName(table string) *fbFundPosition {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.UserID = field.NewInt64(table, "user_id")
	f.FundCode = field.NewString(table, "fund_code")
	f.Amount = field.NewFloat64(table, "amount")
	f.BuyDate = field.NewTime(table, "buy_date")
	f.StartDate = field.NewTime(table, "start_date")
	f.EndDate = field.NewTime(table, "end_date")
	f.Period = field.NewInt32(table, "period")
	f.Rate = field.NewFloat64(table, "rate")
	f.Profit = field.NewFloat64(table, "profit")
	f.State = field.NewString(table, "state")
	f.Status = field.NewBool(table, "status")
	f.CreateTime = field.NewTime(table, "create_time")
	f.UpdateTime = field.NewTime(table, "update_time")
	f.LastProfitDate = field.NewTime(table, "last_profit_date")

	f.fillFieldMap()

	return f
}

func (f *fbFundPosition) WithContext(ctx context.Context) *fbFundPositionDo {
	return f.fbFundPositionDo.WithContext(ctx)
}

func (f fbFundPosition) TableName() string { return f.fbFundPositionDo.TableName() }

func (f fbFundPosition) Alias() string { return f.fbFundPositionDo.Alias() }

func (f fbFundPosition) Columns(cols ...field.Expr) gen.Columns {
	return f.fbFundPositionDo.Columns(cols...)
}

func (f *fbFundPosition) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fbFundPosition) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 15)
	f.fieldMap["id"] = f.ID
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["fund_code"] = f.FundCode
	f.fieldMap["amount"] = f.Amount
	f.fieldMap["buy_date"] = f.BuyDate
	f.fieldMap["start_date"] = f.StartDate
	f.fieldMap["end_date"] = f.EndDate
	f.fieldMap["period"] = f.Period
	f.fieldMap["rate"] = f.Rate
	f.fieldMap["profit"] = f.Profit
	f.fieldMap["state"] = f.State
	f.fieldMap["status"] = f.Status
	f.fieldMap["create_time"] = f.CreateTime
	f.fieldMap["update_time"] = f.UpdateTime
	f.fieldMap["last_profit_date"] = f.LastProfitDate
}

func (f fbFundPosition) clone(db *gorm.DB) fbFundPosition {
	f.fbFundPositionDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fbFundPosition) replaceDB(db *gorm.DB) fbFundPosition {
	f.fbFundPositionDo.ReplaceDB(db)
	return f
}

type fbFundPositionDo struct{ gen.DO }

func (f fbFundPositionDo) Debug() *fbFundPositionDo {
	return f.withDO(f.DO.Debug())
}

func (f fbFundPositionDo) WithContext(ctx context.Context) *fbFundPositionDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fbFundPositionDo) ReadDB() *fbFundPositionDo {
	return f.Clauses(dbresolver.Read)
}

func (f fbFundPositionDo) WriteDB() *fbFundPositionDo {
	return f.Clauses(dbresolver.Write)
}

func (f fbFundPositionDo) Session(config *gorm.Session) *fbFundPositionDo {
	return f.withDO(f.DO.Session(config))
}

func (f fbFundPositionDo) Clauses(conds ...clause.Expression) *fbFundPositionDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fbFundPositionDo) Returning(value interface{}, columns ...string) *fbFundPositionDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fbFundPositionDo) Not(conds ...gen.Condition) *fbFundPositionDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fbFundPositionDo) Or(conds ...gen.Condition) *fbFundPositionDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fbFundPositionDo) Select(conds ...field.Expr) *fbFundPositionDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fbFundPositionDo) Where(conds ...gen.Condition) *fbFundPositionDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fbFundPositionDo) Order(conds ...field.Expr) *fbFundPositionDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fbFundPositionDo) Distinct(cols ...field.Expr) *fbFundPositionDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fbFundPositionDo) Omit(cols ...field.Expr) *fbFundPositionDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fbFundPositionDo) Join(table schema.Tabler, on ...field.Expr) *fbFundPositionDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fbFundPositionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fbFundPositionDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fbFundPositionDo) RightJoin(table schema.Tabler, on ...field.Expr) *fbFundPositionDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fbFundPositionDo) Group(cols ...field.Expr) *fbFundPositionDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fbFundPositionDo) Having(conds ...gen.Condition) *fbFundPositionDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fbFundPositionDo) Limit(limit int) *fbFundPositionDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fbFundPositionDo) Offset(offset int) *fbFundPositionDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fbFundPositionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fbFundPositionDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fbFundPositionDo) Unscoped() *fbFundPositionDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fbFundPositionDo) Create(values ...*model.FbFundPosition) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fbFundPositionDo) CreateInBatches(values []*model.FbFundPosition, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fbFundPositionDo) Save(values ...*model.FbFundPosition) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fbFundPositionDo) First() (*model.FbFundPosition, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbFundPosition), nil
	}
}

func (f fbFundPositionDo) Take() (*model.FbFundPosition, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbFundPosition), nil
	}
}

func (f fbFundPositionDo) Last() (*model.FbFundPosition, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbFundPosition), nil
	}
}

func (f fbFundPositionDo) Find() ([]*model.FbFundPosition, error) {
	result, err := f.DO.Find()
	return result.([]*model.FbFundPosition), err
}

func (f fbFundPositionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FbFundPosition, err error) {
	buf := make([]*model.FbFundPosition, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fbFundPositionDo) FindInBatches(result *[]*model.FbFundPosition, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fbFundPositionDo) Attrs(attrs ...field.AssignExpr) *fbFundPositionDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fbFundPositionDo) Assign(attrs ...field.AssignExpr) *fbFundPositionDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fbFundPositionDo) Joins(fields ...field.RelationField) *fbFundPositionDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fbFundPositionDo) Preload(fields ...field.RelationField) *fbFundPositionDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fbFundPositionDo) FirstOrInit() (*model.FbFundPosition, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbFundPosition), nil
	}
}

func (f fbFundPositionDo) FirstOrCreate() (*model.FbFundPosition, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbFundPosition), nil
	}
}

func (f fbFundPositionDo) FindByPage(offset int, limit int) (result []*model.FbFundPosition, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fbFundPositionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fbFundPositionDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fbFundPositionDo) Delete(models ...*model.FbFundPosition) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fbFundPositionDo) withDO(do gen.Dao) *fbFundPositionDo {
	f.DO = *do.(*gen.DO)
	return f
}
