// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ovra/app/system/internal/dal/model"
)

func newFbIdentityVerify(db *gorm.DB, opts ...gen.DOOption) fbIdentityVerify {
	_fbIdentityVerify := fbIdentityVerify{}

	_fbIdentityVerify.fbIdentityVerifyDo.UseDB(db, opts...)
	_fbIdentityVerify.fbIdentityVerifyDo.UseModel(&model.FbIdentityVerify{})

	tableName := _fbIdentityVerify.fbIdentityVerifyDo.TableName()
	_fbIdentityVerify.ALL = field.NewAsterisk(tableName)
	_fbIdentityVerify.ID = field.NewInt64(tableName, "id")
	_fbIdentityVerify.UserID = field.NewInt64(tableName, "user_id")
	_fbIdentityVerify.RealName = field.NewString(tableName, "real_name")
	_fbIdentityVerify.IDCardNo = field.NewString(tableName, "id_card_no")
	_fbIdentityVerify.IDCardFront = field.NewString(tableName, "id_card_front")
	_fbIdentityVerify.IDCardBack = field.NewString(tableName, "id_card_back")
	_fbIdentityVerify.Status = field.NewString(tableName, "status")
	_fbIdentityVerify.RejectReason = field.NewString(tableName, "reject_reason")
	_fbIdentityVerify.VerifiedAt = field.NewTime(tableName, "verified_at")
	_fbIdentityVerify.CreatedAt = field.NewTime(tableName, "created_at")
	_fbIdentityVerify.UpdatedAt = field.NewTime(tableName, "updated_at")

	_fbIdentityVerify.fillFieldMap()

	return _fbIdentityVerify
}

// fbIdentityVerify 实名认证表
type fbIdentityVerify struct {
	fbIdentityVerifyDo fbIdentityVerifyDo

	ALL          field.Asterisk
	ID           field.Int64  // 主键ID
	UserID       field.Int64  // 用户ID
	RealName     field.String // 真实姓名
	IDCardNo     field.String // 身份证号
	IDCardFront  field.String // 身份证正面照片
	IDCardBack   field.String // 身份证反面照片
	Status       field.String // 认证状态：PENDING-待审核 VERIFIED-已通过 REJECTED-已拒绝
	RejectReason field.String // 拒绝原因
	VerifiedAt   field.Time   // 认证通过/拒绝时间
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (f fbIdentityVerify) Table(newTableName string) *fbIdentityVerify {
	f.fbIdentityVerifyDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fbIdentityVerify) As(alias string) *fbIdentityVerify {
	f.fbIdentityVerifyDo.DO = *(f.fbIdentityVerifyDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fbIdentityVerify) updateTableName(table string) *fbIdentityVerify {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.UserID = field.NewInt64(table, "user_id")
	f.RealName = field.NewString(table, "real_name")
	f.IDCardNo = field.NewString(table, "id_card_no")
	f.IDCardFront = field.NewString(table, "id_card_front")
	f.IDCardBack = field.NewString(table, "id_card_back")
	f.Status = field.NewString(table, "status")
	f.RejectReason = field.NewString(table, "reject_reason")
	f.VerifiedAt = field.NewTime(table, "verified_at")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *fbIdentityVerify) WithContext(ctx context.Context) *fbIdentityVerifyDo {
	return f.fbIdentityVerifyDo.WithContext(ctx)
}

func (f fbIdentityVerify) TableName() string { return f.fbIdentityVerifyDo.TableName() }

func (f fbIdentityVerify) Alias() string { return f.fbIdentityVerifyDo.Alias() }

func (f fbIdentityVerify) Columns(cols ...field.Expr) gen.Columns {
	return f.fbIdentityVerifyDo.Columns(cols...)
}

func (f *fbIdentityVerify) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fbIdentityVerify) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 11)
	f.fieldMap["id"] = f.ID
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["real_name"] = f.RealName
	f.fieldMap["id_card_no"] = f.IDCardNo
	f.fieldMap["id_card_front"] = f.IDCardFront
	f.fieldMap["id_card_back"] = f.IDCardBack
	f.fieldMap["status"] = f.Status
	f.fieldMap["reject_reason"] = f.RejectReason
	f.fieldMap["verified_at"] = f.VerifiedAt
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f fbIdentityVerify) clone(db *gorm.DB) fbIdentityVerify {
	f.fbIdentityVerifyDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fbIdentityVerify) replaceDB(db *gorm.DB) fbIdentityVerify {
	f.fbIdentityVerifyDo.ReplaceDB(db)
	return f
}

type fbIdentityVerifyDo struct{ gen.DO }

func (f fbIdentityVerifyDo) Debug() *fbIdentityVerifyDo {
	return f.withDO(f.DO.Debug())
}

func (f fbIdentityVerifyDo) WithContext(ctx context.Context) *fbIdentityVerifyDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fbIdentityVerifyDo) ReadDB() *fbIdentityVerifyDo {
	return f.Clauses(dbresolver.Read)
}

func (f fbIdentityVerifyDo) WriteDB() *fbIdentityVerifyDo {
	return f.Clauses(dbresolver.Write)
}

func (f fbIdentityVerifyDo) Session(config *gorm.Session) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Session(config))
}

func (f fbIdentityVerifyDo) Clauses(conds ...clause.Expression) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fbIdentityVerifyDo) Returning(value interface{}, columns ...string) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fbIdentityVerifyDo) Not(conds ...gen.Condition) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fbIdentityVerifyDo) Or(conds ...gen.Condition) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fbIdentityVerifyDo) Select(conds ...field.Expr) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fbIdentityVerifyDo) Where(conds ...gen.Condition) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fbIdentityVerifyDo) Order(conds ...field.Expr) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fbIdentityVerifyDo) Distinct(cols ...field.Expr) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fbIdentityVerifyDo) Omit(cols ...field.Expr) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fbIdentityVerifyDo) Join(table schema.Tabler, on ...field.Expr) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fbIdentityVerifyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fbIdentityVerifyDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fbIdentityVerifyDo) RightJoin(table schema.Tabler, on ...field.Expr) *fbIdentityVerifyDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fbIdentityVerifyDo) Group(cols ...field.Expr) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fbIdentityVerifyDo) Having(conds ...gen.Condition) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fbIdentityVerifyDo) Limit(limit int) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fbIdentityVerifyDo) Offset(offset int) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fbIdentityVerifyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fbIdentityVerifyDo) Unscoped() *fbIdentityVerifyDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fbIdentityVerifyDo) Create(values ...*model.FbIdentityVerify) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fbIdentityVerifyDo) CreateInBatches(values []*model.FbIdentityVerify, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fbIdentityVerifyDo) Save(values ...*model.FbIdentityVerify) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fbIdentityVerifyDo) First() (*model.FbIdentityVerify, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbIdentityVerify), nil
	}
}

func (f fbIdentityVerifyDo) Take() (*model.FbIdentityVerify, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbIdentityVerify), nil
	}
}

func (f fbIdentityVerifyDo) Last() (*model.FbIdentityVerify, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbIdentityVerify), nil
	}
}

func (f fbIdentityVerifyDo) Find() ([]*model.FbIdentityVerify, error) {
	result, err := f.DO.Find()
	return result.([]*model.FbIdentityVerify), err
}

func (f fbIdentityVerifyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FbIdentityVerify, err error) {
	buf := make([]*model.FbIdentityVerify, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fbIdentityVerifyDo) FindInBatches(result *[]*model.FbIdentityVerify, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fbIdentityVerifyDo) Attrs(attrs ...field.AssignExpr) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fbIdentityVerifyDo) Assign(attrs ...field.AssignExpr) *fbIdentityVerifyDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fbIdentityVerifyDo) Joins(fields ...field.RelationField) *fbIdentityVerifyDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fbIdentityVerifyDo) Preload(fields ...field.RelationField) *fbIdentityVerifyDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fbIdentityVerifyDo) FirstOrInit() (*model.FbIdentityVerify, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbIdentityVerify), nil
	}
}

func (f fbIdentityVerifyDo) FirstOrCreate() (*model.FbIdentityVerify, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbIdentityVerify), nil
	}
}

func (f fbIdentityVerifyDo) FindByPage(offset int, limit int) (result []*model.FbIdentityVerify, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fbIdentityVerifyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fbIdentityVerifyDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fbIdentityVerifyDo) Delete(models ...*model.FbIdentityVerify) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fbIdentityVerifyDo) withDO(do gen.Dao) *fbIdentityVerifyDo {
	f.DO = *do.(*gen.DO)
	return f
}
