// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ovra/app/system/internal/dal/model"
)

func newFbUser(db *gorm.DB, opts ...gen.DOOption) fbUser {
	_fbUser := fbUser{}

	_fbUser.fbUserDo.UseDB(db, opts...)
	_fbUser.fbUserDo.UseModel(&model.FbUser{})

	tableName := _fbUser.fbUserDo.TableName()
	_fbUser.ALL = field.NewAsterisk(tableName)
	_fbUser.ID = field.NewInt64(tableName, "id")
	_fbUser.Username = field.NewString(tableName, "username")
	_fbUser.Password = field.NewString(tableName, "password")
	_fbUser.Email = field.NewString(tableName, "email")
	_fbUser.Mobile = field.NewString(tableName, "mobile")
	_fbUser.Phone = field.NewString(tableName, "phone")
	_fbUser.RealName = field.NewString(tableName, "real_name")
	_fbUser.IDCard = field.NewString(tableName, "id_card")
	_fbUser.VerificationStatus = field.NewString(tableName, "verification_status")
	_fbUser.CreditScore = field.NewInt32(tableName, "credit_score")
	_fbUser.SecurityQuestion = field.NewString(tableName, "security_question")
	_fbUser.SecurityAnswer = field.NewString(tableName, "security_answer")
	_fbUser.Role = field.NewString(tableName, "role")
	_fbUser.AccountLocked = field.NewBool(tableName, "account_locked")
	_fbUser.FailedAttempts = field.NewInt32(tableName, "failed_attempts")
	_fbUser.LastLogin = field.NewTime(tableName, "last_login")
	_fbUser.ParentID = field.NewInt64(tableName, "parent_id")
	_fbUser.Level = field.NewInt32(tableName, "level")
	_fbUser.AgentLevel = field.NewInt32(tableName, "agent_level")
	_fbUser.InviteCode = field.NewString(tableName, "invite_code")
	_fbUser.CommissionRate = field.NewFloat64(tableName, "commission_rate")
	_fbUser.TotalCommission = field.NewFloat64(tableName, "total_commission")
	_fbUser.TeamSize = field.NewInt32(tableName, "team_size")
	_fbUser.CreatedAt = field.NewTime(tableName, "created_at")
	_fbUser.UpdatedAt = field.NewTime(tableName, "updated_at")
	_fbUser.Status = field.NewString(tableName, "status")
	_fbUser.Verified = field.NewBool(tableName, "verified")
	_fbUser.PayPassword = field.NewString(tableName, "pay_password")
	_fbUser.PayPasswordUpdatedAt = field.NewTime(tableName, "pay_password_updated_at")
	_fbUser.PayPasswordErrorCount = field.NewInt32(tableName, "pay_password_error_count")
	_fbUser.PayPasswordLockedUntil = field.NewTime(tableName, "pay_password_locked_until")
	_fbUser.Avatar = field.NewString(tableName, "avatar")
	_fbUser.ContractControl = field.NewInt32(tableName, "contract_control")
	_fbUser.IsOnline = field.NewString(tableName, "is_online")
	_fbUser.Remark = field.NewString(tableName, "remark")
	_fbUser.Flag = field.NewInt32(tableName, "flag")
	_fbUser.IsTest = field.NewBool(tableName, "is_test")

	_fbUser.fillFieldMap()

	return _fbUser
}

// fbUser 用户表
type fbUser struct {
	fbUserDo fbUserDo

	ALL                    field.Asterisk
	ID                     field.Int64   // 用户ID
	Username               field.String  // 用户名
	Password               field.String  // 密码
	Email                  field.String  // 邮箱
	Mobile                 field.String  // 手机号
	Phone                  field.String  // 手机号
	RealName               field.String  // 真实姓名
	IDCard                 field.String  // 身份证号
	VerificationStatus     field.String  // 实名认证状态
	CreditScore            field.Int32   // 信用分数
	SecurityQuestion       field.String  // 密保问题
	SecurityAnswer         field.String  // 密保答案
	Role                   field.String  // 用户角色
	AccountLocked          field.Bool    // 账户是否锁定
	FailedAttempts         field.Int32   // 登录失败次数
	LastLogin              field.Time    // 最后登录时间
	ParentID               field.Int64   // 上级代理ID
	Level                  field.Int32   // 代理等级
	AgentLevel             field.Int32   // 团队代理层级：3=仅三级；4=含四级；5=含五级
	InviteCode             field.String  // 邀请码
	CommissionRate         field.Float64 // 佣金比例
	TotalCommission        field.Float64 // 累计佣金
	TeamSize               field.Int32   // 团队规模
	CreatedAt              field.Time    // 创建时间
	UpdatedAt              field.Time    // 更新时间
	Status                 field.String  // 用户状态
	Verified               field.Bool    // 是否已实名认证：0-未认证 1-已认证
	PayPassword            field.String  // 交易密码(MD5加密)
	PayPasswordUpdatedAt   field.Time    // 交易密码最后更新时间
	PayPasswordErrorCount  field.Int32   // 交易密码错误次数
	PayPasswordLockedUntil field.Time    // 交易密码锁定截止时间
	Avatar                 field.String  // 用户头像(base64)
	ContractControl        field.Int32   // 合约控制 1 = 赢  2 = 输  3 = 自然
	IsOnline               field.String
	Remark                 field.String // 说明
	Flag                   field.Int32  // 0正常1删除
	IsTest                 field.Bool   // 是否测试账号：0-正式 1-测试

	fieldMap map[string]field.Expr
}

func (f fbUser) Table(newTableName string) *fbUser {
	f.fbUserDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fbUser) As(alias string) *fbUser {
	f.fbUserDo.DO = *(f.fbUserDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fbUser) updateTableName(table string) *fbUser {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.Username = field.NewString(table, "username")
	f.Password = field.NewString(table, "password")
	f.Email = field.NewString(table, "email")
	f.Mobile = field.NewString(table, "mobile")
	f.Phone = field.NewString(table, "phone")
	f.RealName = field.NewString(table, "real_name")
	f.IDCard = field.NewString(table, "id_card")
	f.VerificationStatus = field.NewString(table, "verification_status")
	f.CreditScore = field.NewInt32(table, "credit_score")
	f.SecurityQuestion = field.NewString(table, "security_question")
	f.SecurityAnswer = field.NewString(table, "security_answer")
	f.Role = field.NewString(table, "role")
	f.AccountLocked = field.NewBool(table, "account_locked")
	f.FailedAttempts = field.NewInt32(table, "failed_attempts")
	f.LastLogin = field.NewTime(table, "last_login")
	f.ParentID = field.NewInt64(table, "parent_id")
	f.Level = field.NewInt32(table, "level")
	f.AgentLevel = field.NewInt32(table, "agent_level")
	f.InviteCode = field.NewString(table, "invite_code")
	f.CommissionRate = field.NewFloat64(table, "commission_rate")
	f.TotalCommission = field.NewFloat64(table, "total_commission")
	f.TeamSize = field.NewInt32(table, "team_size")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.Status = field.NewString(table, "status")
	f.Verified = field.NewBool(table, "verified")
	f.PayPassword = field.NewString(table, "pay_password")
	f.PayPasswordUpdatedAt = field.NewTime(table, "pay_password_updated_at")
	f.PayPasswordErrorCount = field.NewInt32(table, "pay_password_error_count")
	f.PayPasswordLockedUntil = field.NewTime(table, "pay_password_locked_until")
	f.Avatar = field.NewString(table, "avatar")
	f.ContractControl = field.NewInt32(table, "contract_control")
	f.IsOnline = field.NewString(table, "is_online")
	f.Remark = field.NewString(table, "remark")
	f.Flag = field.NewInt32(table, "flag")
	f.IsTest = field.NewBool(table, "is_test")

	f.fillFieldMap()

	return f
}

func (f *fbUser) WithContext(ctx context.Context) *fbUserDo { return f.fbUserDo.WithContext(ctx) }

func (f fbUser) TableName() string { return f.fbUserDo.TableName() }

func (f fbUser) Alias() string { return f.fbUserDo.Alias() }

func (f fbUser) Columns(cols ...field.Expr) gen.Columns { return f.fbUserDo.Columns(cols...) }

func (f *fbUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fbUser) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 37)
	f.fieldMap["id"] = f.ID
	f.fieldMap["username"] = f.Username
	f.fieldMap["password"] = f.Password
	f.fieldMap["email"] = f.Email
	f.fieldMap["mobile"] = f.Mobile
	f.fieldMap["phone"] = f.Phone
	f.fieldMap["real_name"] = f.RealName
	f.fieldMap["id_card"] = f.IDCard
	f.fieldMap["verification_status"] = f.VerificationStatus
	f.fieldMap["credit_score"] = f.CreditScore
	f.fieldMap["security_question"] = f.SecurityQuestion
	f.fieldMap["security_answer"] = f.SecurityAnswer
	f.fieldMap["role"] = f.Role
	f.fieldMap["account_locked"] = f.AccountLocked
	f.fieldMap["failed_attempts"] = f.FailedAttempts
	f.fieldMap["last_login"] = f.LastLogin
	f.fieldMap["parent_id"] = f.ParentID
	f.fieldMap["level"] = f.Level
	f.fieldMap["agent_level"] = f.AgentLevel
	f.fieldMap["invite_code"] = f.InviteCode
	f.fieldMap["commission_rate"] = f.CommissionRate
	f.fieldMap["total_commission"] = f.TotalCommission
	f.fieldMap["team_size"] = f.TeamSize
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["status"] = f.Status
	f.fieldMap["verified"] = f.Verified
	f.fieldMap["pay_password"] = f.PayPassword
	f.fieldMap["pay_password_updated_at"] = f.PayPasswordUpdatedAt
	f.fieldMap["pay_password_error_count"] = f.PayPasswordErrorCount
	f.fieldMap["pay_password_locked_until"] = f.PayPasswordLockedUntil
	f.fieldMap["avatar"] = f.Avatar
	f.fieldMap["contract_control"] = f.ContractControl
	f.fieldMap["is_online"] = f.IsOnline
	f.fieldMap["remark"] = f.Remark
	f.fieldMap["flag"] = f.Flag
	f.fieldMap["is_test"] = f.IsTest
}

func (f fbUser) clone(db *gorm.DB) fbUser {
	f.fbUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fbUser) replaceDB(db *gorm.DB) fbUser {
	f.fbUserDo.ReplaceDB(db)
	return f
}

type fbUserDo struct{ gen.DO }

func (f fbUserDo) Debug() *fbUserDo {
	return f.withDO(f.DO.Debug())
}

func (f fbUserDo) WithContext(ctx context.Context) *fbUserDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fbUserDo) ReadDB() *fbUserDo {
	return f.Clauses(dbresolver.Read)
}

func (f fbUserDo) WriteDB() *fbUserDo {
	return f.Clauses(dbresolver.Write)
}

func (f fbUserDo) Session(config *gorm.Session) *fbUserDo {
	return f.withDO(f.DO.Session(config))
}

func (f fbUserDo) Clauses(conds ...clause.Expression) *fbUserDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fbUserDo) Returning(value interface{}, columns ...string) *fbUserDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fbUserDo) Not(conds ...gen.Condition) *fbUserDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fbUserDo) Or(conds ...gen.Condition) *fbUserDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fbUserDo) Select(conds ...field.Expr) *fbUserDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fbUserDo) Where(conds ...gen.Condition) *fbUserDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fbUserDo) Order(conds ...field.Expr) *fbUserDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fbUserDo) Distinct(cols ...field.Expr) *fbUserDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fbUserDo) Omit(cols ...field.Expr) *fbUserDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fbUserDo) Join(table schema.Tabler, on ...field.Expr) *fbUserDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fbUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fbUserDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fbUserDo) RightJoin(table schema.Tabler, on ...field.Expr) *fbUserDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fbUserDo) Group(cols ...field.Expr) *fbUserDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fbUserDo) Having(conds ...gen.Condition) *fbUserDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fbUserDo) Limit(limit int) *fbUserDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fbUserDo) Offset(offset int) *fbUserDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fbUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fbUserDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fbUserDo) Unscoped() *fbUserDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fbUserDo) Create(values ...*model.FbUser) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fbUserDo) CreateInBatches(values []*model.FbUser, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fbUserDo) Save(values ...*model.FbUser) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fbUserDo) First() (*model.FbUser, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbUser), nil
	}
}

func (f fbUserDo) Take() (*model.FbUser, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbUser), nil
	}
}

func (f fbUserDo) Last() (*model.FbUser, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbUser), nil
	}
}

func (f fbUserDo) Find() ([]*model.FbUser, error) {
	result, err := f.DO.Find()
	return result.([]*model.FbUser), err
}

func (f fbUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FbUser, err error) {
	buf := make([]*model.FbUser, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fbUserDo) FindInBatches(result *[]*model.FbUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fbUserDo) Attrs(attrs ...field.AssignExpr) *fbUserDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fbUserDo) Assign(attrs ...field.AssignExpr) *fbUserDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fbUserDo) Joins(fields ...field.RelationField) *fbUserDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fbUserDo) Preload(fields ...field.RelationField) *fbUserDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fbUserDo) FirstOrInit() (*model.FbUser, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbUser), nil
	}
}

func (f fbUserDo) FirstOrCreate() (*model.FbUser, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbUser), nil
	}
}

func (f fbUserDo) FindByPage(offset int, limit int) (result []*model.FbUser, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fbUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fbUserDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fbUserDo) Delete(models ...*model.FbUser) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fbUserDo) withDO(do gen.Dao) *fbUserDo {
	f.DO = *do.(*gen.DO)
	return f
}
