// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ovra/app/system/internal/dal/model"
)

func newFbUserWallet(db *gorm.DB, opts ...gen.DOOption) fbUserWallet {
	_fbUserWallet := fbUserWallet{}

	_fbUserWallet.fbUserWalletDo.UseDB(db, opts...)
	_fbUserWallet.fbUserWalletDo.UseModel(&model.FbUserWallet{})

	tableName := _fbUserWallet.fbUserWalletDo.TableName()
	_fbUserWallet.ALL = field.NewAsterisk(tableName)
	_fbUserWallet.ID = field.NewInt64(tableName, "id")
	_fbUserWallet.UserID = field.NewInt64(tableName, "user_id")
	_fbUserWallet.AccountType = field.NewString(tableName, "account_type")
	_fbUserWallet.Balance = field.NewFloat64(tableName, "balance")
	_fbUserWallet.FrozenAmount = field.NewFloat64(tableName, "frozen_amount")
	_fbUserWallet.Frozen = field.NewBool(tableName, "frozen")
	_fbUserWallet.CreatedAt = field.NewTime(tableName, "created_at")
	_fbUserWallet.UpdatedAt = field.NewTime(tableName, "updated_at")
	_fbUserWallet.Version = field.NewInt64(tableName, "version")
	_fbUserWallet.Currency = field.NewString(tableName, "currency")
	_fbUserWallet.DrawTicket = field.NewInt32(tableName, "draw_ticket")

	_fbUserWallet.fillFieldMap()

	return _fbUserWallet
}

// fbUserWallet 用户钱包表
type fbUserWallet struct {
	fbUserWalletDo fbUserWalletDo

	ALL          field.Asterisk
	ID           field.Int64   // 钱包ID
	UserID       field.Int64   // 用户ID
	AccountType  field.String  // 账户类型：STOCK-股票账户，FOREX-外汇账户，FUTURES-期货账户
	Balance      field.Float64 // 余额
	FrozenAmount field.Float64 // 冻结金额
	Frozen       field.Bool    // 是否冻结
	CreatedAt    field.Time    // 创建时间
	UpdatedAt    field.Time    // 更新时间
	Version      field.Int64   // 版本号
	Currency     field.String  // 种类
	DrawTicket   field.Int32   // 抽奖券数量

	fieldMap map[string]field.Expr
}

func (f fbUserWallet) Table(newTableName string) *fbUserWallet {
	f.fbUserWalletDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fbUserWallet) As(alias string) *fbUserWallet {
	f.fbUserWalletDo.DO = *(f.fbUserWalletDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fbUserWallet) updateTableName(table string) *fbUserWallet {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.UserID = field.NewInt64(table, "user_id")
	f.AccountType = field.NewString(table, "account_type")
	f.Balance = field.NewFloat64(table, "balance")
	f.FrozenAmount = field.NewFloat64(table, "frozen_amount")
	f.Frozen = field.NewBool(table, "frozen")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.Version = field.NewInt64(table, "version")
	f.Currency = field.NewString(table, "currency")
	f.DrawTicket = field.NewInt32(table, "draw_ticket")

	f.fillFieldMap()

	return f
}

func (f *fbUserWallet) WithContext(ctx context.Context) *fbUserWalletDo {
	return f.fbUserWalletDo.WithContext(ctx)
}

func (f fbUserWallet) TableName() string { return f.fbUserWalletDo.TableName() }

func (f fbUserWallet) Alias() string { return f.fbUserWalletDo.Alias() }

func (f fbUserWallet) Columns(cols ...field.Expr) gen.Columns {
	return f.fbUserWalletDo.Columns(cols...)
}

func (f *fbUserWallet) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fbUserWallet) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 11)
	f.fieldMap["id"] = f.ID
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["account_type"] = f.AccountType
	f.fieldMap["balance"] = f.Balance
	f.fieldMap["frozen_amount"] = f.FrozenAmount
	f.fieldMap["frozen"] = f.Frozen
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["version"] = f.Version
	f.fieldMap["currency"] = f.Currency
	f.fieldMap["draw_ticket"] = f.DrawTicket
}

func (f fbUserWallet) clone(db *gorm.DB) fbUserWallet {
	f.fbUserWalletDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fbUserWallet) replaceDB(db *gorm.DB) fbUserWallet {
	f.fbUserWalletDo.ReplaceDB(db)
	return f
}

type fbUserWalletDo struct{ gen.DO }

func (f fbUserWalletDo) Debug() *fbUserWalletDo {
	return f.withDO(f.DO.Debug())
}

func (f fbUserWalletDo) WithContext(ctx context.Context) *fbUserWalletDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fbUserWalletDo) ReadDB() *fbUserWalletDo {
	return f.Clauses(dbresolver.Read)
}

func (f fbUserWalletDo) WriteDB() *fbUserWalletDo {
	return f.Clauses(dbresolver.Write)
}

func (f fbUserWalletDo) Session(config *gorm.Session) *fbUserWalletDo {
	return f.withDO(f.DO.Session(config))
}

func (f fbUserWalletDo) Clauses(conds ...clause.Expression) *fbUserWalletDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fbUserWalletDo) Returning(value interface{}, columns ...string) *fbUserWalletDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fbUserWalletDo) Not(conds ...gen.Condition) *fbUserWalletDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fbUserWalletDo) Or(conds ...gen.Condition) *fbUserWalletDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fbUserWalletDo) Select(conds ...field.Expr) *fbUserWalletDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fbUserWalletDo) Where(conds ...gen.Condition) *fbUserWalletDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fbUserWalletDo) Order(conds ...field.Expr) *fbUserWalletDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fbUserWalletDo) Distinct(cols ...field.Expr) *fbUserWalletDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fbUserWalletDo) Omit(cols ...field.Expr) *fbUserWalletDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fbUserWalletDo) Join(table schema.Tabler, on ...field.Expr) *fbUserWalletDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fbUserWalletDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fbUserWalletDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fbUserWalletDo) RightJoin(table schema.Tabler, on ...field.Expr) *fbUserWalletDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fbUserWalletDo) Group(cols ...field.Expr) *fbUserWalletDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fbUserWalletDo) Having(conds ...gen.Condition) *fbUserWalletDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fbUserWalletDo) Limit(limit int) *fbUserWalletDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fbUserWalletDo) Offset(offset int) *fbUserWalletDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fbUserWalletDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fbUserWalletDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fbUserWalletDo) Unscoped() *fbUserWalletDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fbUserWalletDo) Create(values ...*model.FbUserWallet) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fbUserWalletDo) CreateInBatches(values []*model.FbUserWallet, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fbUserWalletDo) Save(values ...*model.FbUserWallet) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fbUserWalletDo) First() (*model.FbUserWallet, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbUserWallet), nil
	}
}

func (f fbUserWalletDo) Take() (*model.FbUserWallet, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbUserWallet), nil
	}
}

func (f fbUserWalletDo) Last() (*model.FbUserWallet, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbUserWallet), nil
	}
}

func (f fbUserWalletDo) Find() ([]*model.FbUserWallet, error) {
	result, err := f.DO.Find()
	return result.([]*model.FbUserWallet), err
}

func (f fbUserWalletDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FbUserWallet, err error) {
	buf := make([]*model.FbUserWallet, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fbUserWalletDo) FindInBatches(result *[]*model.FbUserWallet, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fbUserWalletDo) Attrs(attrs ...field.AssignExpr) *fbUserWalletDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fbUserWalletDo) Assign(attrs ...field.AssignExpr) *fbUserWalletDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fbUserWalletDo) Joins(fields ...field.RelationField) *fbUserWalletDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fbUserWalletDo) Preload(fields ...field.RelationField) *fbUserWalletDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fbUserWalletDo) FirstOrInit() (*model.FbUserWallet, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbUserWallet), nil
	}
}

func (f fbUserWalletDo) FirstOrCreate() (*model.FbUserWallet, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbUserWallet), nil
	}
}

func (f fbUserWalletDo) FindByPage(offset int, limit int) (result []*model.FbUserWallet, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fbUserWalletDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fbUserWalletDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fbUserWalletDo) Delete(models ...*model.FbUserWallet) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fbUserWalletDo) withDO(do gen.Dao) *fbUserWalletDo {
	f.DO = *do.(*gen.DO)
	return f
}
