// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ovra/app/system/internal/dal/model"
)

func newFbWithdraw(db *gorm.DB, opts ...gen.DOOption) fbWithdraw {
	_fbWithdraw := fbWithdraw{}

	_fbWithdraw.fbWithdrawDo.UseDB(db, opts...)
	_fbWithdraw.fbWithdrawDo.UseModel(&model.FbWithdraw{})

	tableName := _fbWithdraw.fbWithdrawDo.TableName()
	_fbWithdraw.ALL = field.NewAsterisk(tableName)
	_fbWithdraw.ID = field.NewInt64(tableName, "id")
	_fbWithdraw.UserID = field.NewInt64(tableName, "user_id")
	_fbWithdraw.OrderNo = field.NewString(tableName, "order_no")
	_fbWithdraw.Amount = field.NewFloat64(tableName, "amount")
	_fbWithdraw.Status = field.NewString(tableName, "status")
	_fbWithdraw.BankName = field.NewString(tableName, "bank_name")
	_fbWithdraw.BankCardNo = field.NewString(tableName, "bank_card_no")
	_fbWithdraw.AccountName = field.NewString(tableName, "account_name")
	_fbWithdraw.PaymentStatus = field.NewString(tableName, "payment_status")
	_fbWithdraw.PaymentNo = field.NewString(tableName, "payment_no")
	_fbWithdraw.PaymentTime = field.NewTime(tableName, "payment_time")
	_fbWithdraw.Remark = field.NewString(tableName, "remark")
	_fbWithdraw.RejectReason = field.NewString(tableName, "reject_reason")
	_fbWithdraw.CreatedAt = field.NewTime(tableName, "created_at")
	_fbWithdraw.UpdatedAt = field.NewTime(tableName, "updated_at")
	_fbWithdraw.WithdrawType = field.NewString(tableName, "withdraw_type")

	_fbWithdraw.fillFieldMap()

	return _fbWithdraw
}

// fbWithdraw 提现记录表
type fbWithdraw struct {
	fbWithdrawDo fbWithdrawDo

	ALL           field.Asterisk
	ID            field.Int64
	UserID        field.Int64   // 用户ID
	OrderNo       field.String  // 订单号
	Amount        field.Float64 // 提现金额
	Status        field.String  // 状态
	BankName      field.String  // 银行名称
	BankCardNo    field.String  // 银行卡号
	AccountName   field.String  // 开户名
	PaymentStatus field.String  // 支付状态
	PaymentNo     field.String  // 银行转账流水号
	PaymentTime   field.Time    // 支付时间
	Remark        field.String  // 备注
	RejectReason  field.String  // 拒绝原因
	CreatedAt     field.Time
	UpdatedAt     field.Time
	WithdrawType  field.String

	fieldMap map[string]field.Expr
}

func (f fbWithdraw) Table(newTableName string) *fbWithdraw {
	f.fbWithdrawDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fbWithdraw) As(alias string) *fbWithdraw {
	f.fbWithdrawDo.DO = *(f.fbWithdrawDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fbWithdraw) updateTableName(table string) *fbWithdraw {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.UserID = field.NewInt64(table, "user_id")
	f.OrderNo = field.NewString(table, "order_no")
	f.Amount = field.NewFloat64(table, "amount")
	f.Status = field.NewString(table, "status")
	f.BankName = field.NewString(table, "bank_name")
	f.BankCardNo = field.NewString(table, "bank_card_no")
	f.AccountName = field.NewString(table, "account_name")
	f.PaymentStatus = field.NewString(table, "payment_status")
	f.PaymentNo = field.NewString(table, "payment_no")
	f.PaymentTime = field.NewTime(table, "payment_time")
	f.Remark = field.NewString(table, "remark")
	f.RejectReason = field.NewString(table, "reject_reason")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.WithdrawType = field.NewString(table, "withdraw_type")

	f.fillFieldMap()

	return f
}

func (f *fbWithdraw) WithContext(ctx context.Context) *fbWithdrawDo {
	return f.fbWithdrawDo.WithContext(ctx)
}

func (f fbWithdraw) TableName() string { return f.fbWithdrawDo.TableName() }

func (f fbWithdraw) Alias() string { return f.fbWithdrawDo.Alias() }

func (f fbWithdraw) Columns(cols ...field.Expr) gen.Columns { return f.fbWithdrawDo.Columns(cols...) }

func (f *fbWithdraw) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fbWithdraw) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 16)
	f.fieldMap["id"] = f.ID
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["order_no"] = f.OrderNo
	f.fieldMap["amount"] = f.Amount
	f.fieldMap["status"] = f.Status
	f.fieldMap["bank_name"] = f.BankName
	f.fieldMap["bank_card_no"] = f.BankCardNo
	f.fieldMap["account_name"] = f.AccountName
	f.fieldMap["payment_status"] = f.PaymentStatus
	f.fieldMap["payment_no"] = f.PaymentNo
	f.fieldMap["payment_time"] = f.PaymentTime
	f.fieldMap["remark"] = f.Remark
	f.fieldMap["reject_reason"] = f.RejectReason
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["withdraw_type"] = f.WithdrawType
}

func (f fbWithdraw) clone(db *gorm.DB) fbWithdraw {
	f.fbWithdrawDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fbWithdraw) replaceDB(db *gorm.DB) fbWithdraw {
	f.fbWithdrawDo.ReplaceDB(db)
	return f
}

type fbWithdrawDo struct{ gen.DO }

func (f fbWithdrawDo) Debug() *fbWithdrawDo {
	return f.withDO(f.DO.Debug())
}

func (f fbWithdrawDo) WithContext(ctx context.Context) *fbWithdrawDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fbWithdrawDo) ReadDB() *fbWithdrawDo {
	return f.Clauses(dbresolver.Read)
}

func (f fbWithdrawDo) WriteDB() *fbWithdrawDo {
	return f.Clauses(dbresolver.Write)
}

func (f fbWithdrawDo) Session(config *gorm.Session) *fbWithdrawDo {
	return f.withDO(f.DO.Session(config))
}

func (f fbWithdrawDo) Clauses(conds ...clause.Expression) *fbWithdrawDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fbWithdrawDo) Returning(value interface{}, columns ...string) *fbWithdrawDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fbWithdrawDo) Not(conds ...gen.Condition) *fbWithdrawDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fbWithdrawDo) Or(conds ...gen.Condition) *fbWithdrawDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fbWithdrawDo) Select(conds ...field.Expr) *fbWithdrawDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fbWithdrawDo) Where(conds ...gen.Condition) *fbWithdrawDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fbWithdrawDo) Order(conds ...field.Expr) *fbWithdrawDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fbWithdrawDo) Distinct(cols ...field.Expr) *fbWithdrawDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fbWithdrawDo) Omit(cols ...field.Expr) *fbWithdrawDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fbWithdrawDo) Join(table schema.Tabler, on ...field.Expr) *fbWithdrawDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fbWithdrawDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fbWithdrawDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fbWithdrawDo) RightJoin(table schema.Tabler, on ...field.Expr) *fbWithdrawDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fbWithdrawDo) Group(cols ...field.Expr) *fbWithdrawDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fbWithdrawDo) Having(conds ...gen.Condition) *fbWithdrawDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fbWithdrawDo) Limit(limit int) *fbWithdrawDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fbWithdrawDo) Offset(offset int) *fbWithdrawDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fbWithdrawDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fbWithdrawDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fbWithdrawDo) Unscoped() *fbWithdrawDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fbWithdrawDo) Create(values ...*model.FbWithdraw) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fbWithdrawDo) CreateInBatches(values []*model.FbWithdraw, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fbWithdrawDo) Save(values ...*model.FbWithdraw) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fbWithdrawDo) First() (*model.FbWithdraw, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbWithdraw), nil
	}
}

func (f fbWithdrawDo) Take() (*model.FbWithdraw, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbWithdraw), nil
	}
}

func (f fbWithdrawDo) Last() (*model.FbWithdraw, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbWithdraw), nil
	}
}

func (f fbWithdrawDo) Find() ([]*model.FbWithdraw, error) {
	result, err := f.DO.Find()
	return result.([]*model.FbWithdraw), err
}

func (f fbWithdrawDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FbWithdraw, err error) {
	buf := make([]*model.FbWithdraw, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fbWithdrawDo) FindInBatches(result *[]*model.FbWithdraw, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fbWithdrawDo) Attrs(attrs ...field.AssignExpr) *fbWithdrawDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fbWithdrawDo) Assign(attrs ...field.AssignExpr) *fbWithdrawDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fbWithdrawDo) Joins(fields ...field.RelationField) *fbWithdrawDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fbWithdrawDo) Preload(fields ...field.RelationField) *fbWithdrawDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fbWithdrawDo) FirstOrInit() (*model.FbWithdraw, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbWithdraw), nil
	}
}

func (f fbWithdrawDo) FirstOrCreate() (*model.FbWithdraw, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FbWithdraw), nil
	}
}

func (f fbWithdrawDo) FindByPage(offset int, limit int) (result []*model.FbWithdraw, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fbWithdrawDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fbWithdrawDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fbWithdrawDo) Delete(models ...*model.FbWithdraw) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fbWithdrawDo) withDO(do gen.Dao) *fbWithdrawDo {
	f.DO = *do.(*gen.DO)
	return f
}
