// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ovra/app/system/internal/dal/model"
)

func newSysTenant(db *gorm.DB, opts ...gen.DOOption) sysTenant {
	_sysTenant := sysTenant{}

	_sysTenant.sysTenantDo.UseDB(db, opts...)
	_sysTenant.sysTenantDo.UseModel(&model.SysTenant{})

	tableName := _sysTenant.sysTenantDo.TableName()
	_sysTenant.ALL = field.NewAsterisk(tableName)
	_sysTenant.ID = field.NewString(tableName, "id")
	_sysTenant.TenantID = field.NewString(tableName, "tenant_id")
	_sysTenant.ContactUsername = field.NewString(tableName, "contact_username")
	_sysTenant.ContactPhone = field.NewString(tableName, "contact_phone")
	_sysTenant.CompanyName = field.NewString(tableName, "company_name")
	_sysTenant.LicenseNumber = field.NewString(tableName, "license_number")
	_sysTenant.Address = field.NewString(tableName, "address")
	_sysTenant.Intro = field.NewString(tableName, "intro")
	_sysTenant.Domain = field.NewString(tableName, "domain")
	_sysTenant.Remark = field.NewString(tableName, "remark")
	_sysTenant.PackageID = field.NewString(tableName, "package_id")
	_sysTenant.ExpireTime = field.NewTime(tableName, "expire_time")
	_sysTenant.AccountCount = field.NewInt32(tableName, "account_count")
	_sysTenant.Status = field.NewString(tableName, "status")
	_sysTenant.DelFlag = field.NewString(tableName, "del_flag")
	_sysTenant.CreateDept = field.NewInt64(tableName, "create_dept")
	_sysTenant.CreateBy = field.NewInt64(tableName, "create_by")
	_sysTenant.CreateTime = field.NewTime(tableName, "create_time")
	_sysTenant.UpdateBy = field.NewInt64(tableName, "update_by")
	_sysTenant.UpdateTime = field.NewTime(tableName, "update_time")

	_sysTenant.fillFieldMap()

	return _sysTenant
}

// sysTenant 租户表
type sysTenant struct {
	sysTenantDo sysTenantDo

	ALL             field.Asterisk
	ID              field.String // id
	TenantID        field.String // 租户编号
	ContactUsername field.String // 联系人
	ContactPhone    field.String // 联系电话
	CompanyName     field.String // 企业名称
	LicenseNumber   field.String // 统一社会信用代码
	Address         field.String // 地址
	Intro           field.String // 企业简介
	Domain          field.String // 域名
	Remark          field.String // 备注
	PackageID       field.String // 套餐ID
	ExpireTime      field.Time   // 过期时间
	AccountCount    field.Int32  // 用户数量（-1不限制）
	Status          field.String // 租户状态（0正常 1停用）
	DelFlag         field.String // 删除标志（0代表存在 1代表删除）
	CreateDept      field.Int64  // 创建部门
	CreateBy        field.Int64  // 创建者
	CreateTime      field.Time   // 创建时间
	UpdateBy        field.Int64  // 更新者
	UpdateTime      field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (s sysTenant) Table(newTableName string) *sysTenant {
	s.sysTenantDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysTenant) As(alias string) *sysTenant {
	s.sysTenantDo.DO = *(s.sysTenantDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysTenant) updateTableName(table string) *sysTenant {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.TenantID = field.NewString(table, "tenant_id")
	s.ContactUsername = field.NewString(table, "contact_username")
	s.ContactPhone = field.NewString(table, "contact_phone")
	s.CompanyName = field.NewString(table, "company_name")
	s.LicenseNumber = field.NewString(table, "license_number")
	s.Address = field.NewString(table, "address")
	s.Intro = field.NewString(table, "intro")
	s.Domain = field.NewString(table, "domain")
	s.Remark = field.NewString(table, "remark")
	s.PackageID = field.NewString(table, "package_id")
	s.ExpireTime = field.NewTime(table, "expire_time")
	s.AccountCount = field.NewInt32(table, "account_count")
	s.Status = field.NewString(table, "status")
	s.DelFlag = field.NewString(table, "del_flag")
	s.CreateDept = field.NewInt64(table, "create_dept")
	s.CreateBy = field.NewInt64(table, "create_by")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateBy = field.NewInt64(table, "update_by")
	s.UpdateTime = field.NewTime(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *sysTenant) WithContext(ctx context.Context) *sysTenantDo {
	return s.sysTenantDo.WithContext(ctx)
}

func (s sysTenant) TableName() string { return s.sysTenantDo.TableName() }

func (s sysTenant) Alias() string { return s.sysTenantDo.Alias() }

func (s sysTenant) Columns(cols ...field.Expr) gen.Columns { return s.sysTenantDo.Columns(cols...) }

func (s *sysTenant) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysTenant) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 20)
	s.fieldMap["id"] = s.ID
	s.fieldMap["tenant_id"] = s.TenantID
	s.fieldMap["contact_username"] = s.ContactUsername
	s.fieldMap["contact_phone"] = s.ContactPhone
	s.fieldMap["company_name"] = s.CompanyName
	s.fieldMap["license_number"] = s.LicenseNumber
	s.fieldMap["address"] = s.Address
	s.fieldMap["intro"] = s.Intro
	s.fieldMap["domain"] = s.Domain
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["package_id"] = s.PackageID
	s.fieldMap["expire_time"] = s.ExpireTime
	s.fieldMap["account_count"] = s.AccountCount
	s.fieldMap["status"] = s.Status
	s.fieldMap["del_flag"] = s.DelFlag
	s.fieldMap["create_dept"] = s.CreateDept
	s.fieldMap["create_by"] = s.CreateBy
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_by"] = s.UpdateBy
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s sysTenant) clone(db *gorm.DB) sysTenant {
	s.sysTenantDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysTenant) replaceDB(db *gorm.DB) sysTenant {
	s.sysTenantDo.ReplaceDB(db)
	return s
}

type sysTenantDo struct{ gen.DO }

func (s sysTenantDo) Debug() *sysTenantDo {
	return s.withDO(s.DO.Debug())
}

func (s sysTenantDo) WithContext(ctx context.Context) *sysTenantDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysTenantDo) ReadDB() *sysTenantDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysTenantDo) WriteDB() *sysTenantDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysTenantDo) Session(config *gorm.Session) *sysTenantDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysTenantDo) Clauses(conds ...clause.Expression) *sysTenantDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysTenantDo) Returning(value interface{}, columns ...string) *sysTenantDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysTenantDo) Not(conds ...gen.Condition) *sysTenantDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysTenantDo) Or(conds ...gen.Condition) *sysTenantDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysTenantDo) Select(conds ...field.Expr) *sysTenantDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysTenantDo) Where(conds ...gen.Condition) *sysTenantDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysTenantDo) Order(conds ...field.Expr) *sysTenantDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysTenantDo) Distinct(cols ...field.Expr) *sysTenantDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysTenantDo) Omit(cols ...field.Expr) *sysTenantDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysTenantDo) Join(table schema.Tabler, on ...field.Expr) *sysTenantDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysTenantDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysTenantDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysTenantDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysTenantDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysTenantDo) Group(cols ...field.Expr) *sysTenantDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysTenantDo) Having(conds ...gen.Condition) *sysTenantDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysTenantDo) Limit(limit int) *sysTenantDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysTenantDo) Offset(offset int) *sysTenantDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysTenantDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysTenantDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysTenantDo) Unscoped() *sysTenantDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysTenantDo) Create(values ...*model.SysTenant) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysTenantDo) CreateInBatches(values []*model.SysTenant, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysTenantDo) Save(values ...*model.SysTenant) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysTenantDo) First() (*model.SysTenant, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTenant), nil
	}
}

func (s sysTenantDo) Take() (*model.SysTenant, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTenant), nil
	}
}

func (s sysTenantDo) Last() (*model.SysTenant, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTenant), nil
	}
}

func (s sysTenantDo) Find() ([]*model.SysTenant, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysTenant), err
}

func (s sysTenantDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysTenant, err error) {
	buf := make([]*model.SysTenant, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysTenantDo) FindInBatches(result *[]*model.SysTenant, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysTenantDo) Attrs(attrs ...field.AssignExpr) *sysTenantDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysTenantDo) Assign(attrs ...field.AssignExpr) *sysTenantDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysTenantDo) Joins(fields ...field.RelationField) *sysTenantDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysTenantDo) Preload(fields ...field.RelationField) *sysTenantDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysTenantDo) FirstOrInit() (*model.SysTenant, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTenant), nil
	}
}

func (s sysTenantDo) FirstOrCreate() (*model.SysTenant, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTenant), nil
	}
}

func (s sysTenantDo) FindByPage(offset int, limit int) (result []*model.SysTenant, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysTenantDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysTenantDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysTenantDo) Delete(models ...*model.SysTenant) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysTenantDo) withDO(do gen.Dao) *sysTenantDo {
	s.DO = *do.(*gen.DO)
	return s
}
