// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.0

package handler

import (
	"net/http"

	appbrand "ovra/app/system/internal/handler/app/brand"
	apprelease "ovra/app/system/internal/handler/app/release"
	appversion "ovra/app/system/internal/handler/app/version"
	devencrypt "ovra/app/system/internal/handler/dev/encrypt"
	devsse "ovra/app/system/internal/handler/dev/sse"
	fundrecharge "ovra/app/system/internal/handler/fund/recharge"
	fundstatement "ovra/app/system/internal/handler/fund/statement"
	fundwalletApply "ovra/app/system/internal/handler/fund/walletApply"
	fundwithdraw "ovra/app/system/internal/handler/fund/withdraw"
	health "ovra/app/system/internal/handler/health"
	investlist "ovra/app/system/internal/handler/invest/list"
	investposition "ovra/app/system/internal/handler/invest/position"
	klinekline "ovra/app/system/internal/handler/kline/kline"
	memberkyc "ovra/app/system/internal/handler/member/kyc"
	memberloginLog "ovra/app/system/internal/handler/member/loginLog"
	memberreport "ovra/app/system/internal/handler/member/report"
	memberteam "ovra/app/system/internal/handler/member/team"
	memberuser "ovra/app/system/internal/handler/member/user"
	memberwallet "ovra/app/system/internal/handler/member/wallet"
	monitorlogininfor "ovra/app/system/internal/handler/monitor/logininfor"
	monitormonitor "ovra/app/system/internal/handler/monitor/monitor"
	monitoronline "ovra/app/system/internal/handler/monitor/online"
	monitoroperLog "ovra/app/system/internal/handler/monitor/operLog"
	notifynews "ovra/app/system/internal/handler/notify/news"
	notifypublish "ovra/app/system/internal/handler/notify/publish"
	productconfig "ovra/app/system/internal/handler/product/config"
	producthistory "ovra/app/system/internal/handler/product/history"
	productrealtime "ovra/app/system/internal/handler/product/realtime"
	resourceoss "ovra/app/system/internal/handler/resource/oss"
	resourceossconfig "ovra/app/system/internal/handler/resource/oss/config"
	system_config "ovra/app/system/internal/handler/system/_config"
	system_post "ovra/app/system/internal/handler/system/_post"
	systemclient "ovra/app/system/internal/handler/system/client"
	systemdept "ovra/app/system/internal/handler/system/dept"
	systemdict_type "ovra/app/system/internal/handler/system/dict/_type"
	systemdictdata "ovra/app/system/internal/handler/system/dict/data"
	systemmenu "ovra/app/system/internal/handler/system/menu"
	systemnotice "ovra/app/system/internal/handler/system/notice"
	systemrole "ovra/app/system/internal/handler/system/role"
	systemtenant "ovra/app/system/internal/handler/system/tenant"
	systemtenant_package "ovra/app/system/internal/handler/system/tenant/_package"
	systemuser "ovra/app/system/internal/handler/system/user"
	tradecontract "ovra/app/system/internal/handler/trade/contract"
	tradedeal "ovra/app/system/internal/handler/trade/deal"
	tradeentrust "ovra/app/system/internal/handler/trade/entrust"
	"ovra/app/system/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/deptTree",
					Handler: systemuser.GetDeptTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/profile",
					Handler: systemuser.ProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getInfo",
					Handler: systemuser.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemuser.QueryUserDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: systemuser.QueryUserDetailInsertHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemuser.AddUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: systemuser.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemuser.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: systemuser.UpdateUserStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/resetPwd",
					Handler: systemuser.ResetPwdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list/dept/:id",
					Handler: systemuser.DeptListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemuser.QueryPageUserListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemrole.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemrole.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: systemrole.RemoveHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemrole.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemrole.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: systemrole.ChangeStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/deptTree/:id",
					Handler: systemrole.DeptTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/authUser/allocatedList",
					Handler: systemrole.AllocatedListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/authUser/unallocatedList",
					Handler: systemrole.UnAllocatedListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/authUser/selectAll",
					Handler: systemrole.SelectAllHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/authUser/cancelAll",
					Handler: systemrole.CancelAllHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/authUser/cancel",
					Handler: systemrole.CancelHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/role"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemdept.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemdept.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: systemdept.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemdept.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list/exclude/:id",
					Handler: systemdept.ExcludeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemdept.ListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/dept"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/treeselect",
					Handler: systemmenu.TreeSelectHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/roleMenuTreeselect/:id",
					Handler: systemmenu.RoleMenuTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tenantPackageMenuTreeselect/:id",
					Handler: systemmenu.TenantPackageTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getRouters",
					Handler: systemmenu.GetRoutersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemmenu.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemmenu.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: systemmenu.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/cascade/:ids",
					Handler: systemmenu.DeleteCascadeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemmenu.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemmenu.ListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/menu"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/deptTree",
					Handler: system_post.GetDeptTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/optionselect",
					Handler: system_post.OptionSelectHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: system_post.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: system_post.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: system_post.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: system_post.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: system_post.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/post"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemnotice.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemnotice.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: systemnotice.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemnotice.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemnotice.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/notice"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemclient.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemclient.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: systemclient.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: systemclient.ChangeStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemclient.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemclient.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/client"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/syncTenantDict",
					Handler: systemtenant.SyncTenantDictHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/syncTenantPackage",
					Handler: systemtenant.SyncTenantPackageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemtenant.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemtenant.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: systemtenant.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: systemtenant.ChangeStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemtenant.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemtenant.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dynamic/clear",
					Handler: systemtenant.ClearHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dynamic/:id",
					Handler: systemtenant.DynamicHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/tenant"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemtenant_package.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemtenant_package.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: systemtenant_package.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: systemtenant_package.ChangeStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemtenant_package.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemtenant_package.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/selectList",
					Handler: systemtenant_package.SelectListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/tenant/package"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/configKey/:code",
					Handler: system_config.ConfigKeyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: system_config.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: system_config.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: system_config.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: system_config.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: system_config.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/config"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/type/:code",
					Handler: systemdictdata.DataByTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemdictdata.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemdictdata.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: systemdictdata.DeleteDictDataHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemdictdata.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemdictdata.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/dict/data"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemdict_type.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemdict_type.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/refreshCache",
					Handler: systemdict_type.RefreshCacheHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: systemdict_type.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemdict_type.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemdict_type.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/dict/type"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: resourceoss.UploadHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: resourceoss.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: resourceoss.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/resource/oss"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: resourceossconfig.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: resourceossconfig.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: resourceossconfig.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: resourceossconfig.ChangeStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: resourceossconfig.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: resourceossconfig.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/resource/oss/config"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: monitoronline.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: monitoronline.OfflineHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor/online"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/clean",
					Handler: monitoroperLog.CleanHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: monitoroperLog.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: monitoroperLog.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor/operlog"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/clean",
					Handler: monitorlogininfor.CleanHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: monitorlogininfor.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: monitorlogininfor.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor/logininfor"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/cache",
					Handler: monitormonitor.RedisMonitorHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/status",
					Handler: devsse.StatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: devsse.ListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/sendAll",
					Handler: devsse.SendAllHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/send/:id",
					Handler: devsse.SendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/sse"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/request",
					Handler: devencrypt.RequestHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/response",
					Handler: devencrypt.ResponseHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/test/api/encrypt"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/stats",
					Handler: memberuser.StatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: memberuser.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: memberuser.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: memberuser.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: memberuser.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/restore/:ids",
					Handler: memberuser.RestoreHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/resetPwd",
					Handler: memberuser.ResetPwdHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/member/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: memberkyc.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/member/kyc"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: memberwallet.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/addOrSubtract",
					Handler: memberwallet.AddOrSubtractHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: memberwallet.DeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/member/wallet"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: memberreport.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/flow/:userId",
					Handler: memberreport.FlowHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/member/report"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/stats",
					Handler: memberteam.StatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: memberteam.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: memberteam.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/members/:userId",
					Handler: memberteam.MembersHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeParent",
					Handler: memberteam.ChangeParentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/agentLevel",
					Handler: memberteam.AgentLevelHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/member/team"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: memberloginLog.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/member/loginLog"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: fundwalletApply.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/detail/:id",
					Handler: fundwalletApply.DetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/flow/currentMonth",
					Handler: fundwalletApply.CurrentMonthFlowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/loginLog/:userId",
					Handler: fundwalletApply.LoginLogHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/fund/walletApply"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: fundstatement.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/detail/:id",
					Handler: fundstatement.DetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/fund/statement"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: fundwithdraw.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/approved/:id",
					Handler: fundwithdraw.ApprovedHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/rejected",
					Handler: fundwithdraw.RejectedHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/fund/withdraw"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: fundrecharge.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/approved/:id",
					Handler: fundrecharge.ApprovedHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/rejected",
					Handler: fundrecharge.RejectedHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/fund/recharge"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: tradecontract.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/win/:id",
					Handler: tradecontract.WinHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/lose/:id",
					Handler: tradecontract.LoseHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/direction/:id/:direction",
					Handler: tradecontract.DirectionHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/control/batch-current-page/directional",
					Handler: tradecontract.BatchCurrentPageDirectionalHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/detail/:id",
					Handler: tradecontract.SettlementDetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/trade/contract"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: tradeentrust.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/trade/entrust"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: tradedeal.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/trade/deal"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: investposition.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/order/list",
					Handler: investposition.OrderPageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/profit/before",
					Handler: investposition.ProfitBeforeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/profit",
					Handler: investposition.UpdateProfitHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/invest/position"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: investlist.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: investlist.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: investlist.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: investlist.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: investlist.DeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/invest/list"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: productconfig.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: productconfig.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: productconfig.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: productconfig.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: productconfig.DeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/product/config"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: productrealtime.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/product/realtime"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: producthistory.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/product/history"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: notifynews.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: notifynews.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: notifynews.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: notifynews.UpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/notify/news"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: notifypublish.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/notify/publish"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: klinekline.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/kline/main"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/active",
					Handler: appbrand.ActiveHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: appbrand.SaveHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/app/brand"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/active",
					Handler: appversion.ActiveHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: appversion.UpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/app/version"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/options",
					Handler: apprelease.OptionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/app/release/upload"),
	)
}
