// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.0

package handler

import (
	"net/http"

	devencrypt "ovra/app/system/internal/handler/dev/encrypt"
	devsse "ovra/app/system/internal/handler/dev/sse"
	health "ovra/app/system/internal/handler/health"
	monitorlogininfor "ovra/app/system/internal/handler/monitor/logininfor"
	monitormonitor "ovra/app/system/internal/handler/monitor/monitor"
	monitoronline "ovra/app/system/internal/handler/monitor/online"
	monitoroperLog "ovra/app/system/internal/handler/monitor/operLog"
	resourceoss "ovra/app/system/internal/handler/resource/oss"
	resourceossconfig "ovra/app/system/internal/handler/resource/oss/config"
	system_config "ovra/app/system/internal/handler/system/_config"
	system_post "ovra/app/system/internal/handler/system/_post"
	systemclient "ovra/app/system/internal/handler/system/client"
	systemdept "ovra/app/system/internal/handler/system/dept"
	systemdict_type "ovra/app/system/internal/handler/system/dict/_type"
	systemdictdata "ovra/app/system/internal/handler/system/dict/data"
	systemmenu "ovra/app/system/internal/handler/system/menu"
	systemnotice "ovra/app/system/internal/handler/system/notice"
	systemrole "ovra/app/system/internal/handler/system/role"
	systemtenant "ovra/app/system/internal/handler/system/tenant"
	systemtenant_package "ovra/app/system/internal/handler/system/tenant/_package"
	systemuser "ovra/app/system/internal/handler/system/user"
	"ovra/app/system/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/deptTree",
					Handler: systemuser.GetDeptTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/profile",
					Handler: systemuser.ProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getInfo",
					Handler: systemuser.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemuser.QueryUserDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: systemuser.QueryUserDetailInsertHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemuser.AddUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: systemuser.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemuser.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: systemuser.UpdateUserStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/resetPwd",
					Handler: systemuser.ResetPwdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list/dept/:id",
					Handler: systemuser.DeptListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemuser.QueryPageUserListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemrole.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemrole.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: systemrole.RemoveHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemrole.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemrole.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: systemrole.ChangeStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/deptTree/:id",
					Handler: systemrole.DeptTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/authUser/allocatedList",
					Handler: systemrole.AllocatedListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/authUser/unallocatedList",
					Handler: systemrole.UnAllocatedListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/authUser/selectAll",
					Handler: systemrole.SelectAllHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/authUser/cancelAll",
					Handler: systemrole.CancelAllHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/authUser/cancel",
					Handler: systemrole.CancelHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/role"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemdept.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemdept.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: systemdept.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemdept.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list/exclude/:id",
					Handler: systemdept.ExcludeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemdept.ListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/dept"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/treeselect",
					Handler: systemmenu.TreeSelectHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/roleMenuTreeselect/:id",
					Handler: systemmenu.RoleMenuTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tenantPackageMenuTreeselect/:id",
					Handler: systemmenu.TenantPackageTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getRouters",
					Handler: systemmenu.GetRoutersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemmenu.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemmenu.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: systemmenu.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/cascade/:ids",
					Handler: systemmenu.DeleteCascadeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemmenu.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemmenu.ListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/menu"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/deptTree",
					Handler: system_post.GetDeptTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/optionselect",
					Handler: system_post.OptionSelectHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: system_post.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: system_post.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: system_post.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: system_post.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: system_post.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/post"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemnotice.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemnotice.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: systemnotice.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemnotice.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemnotice.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/notice"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemclient.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemclient.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: systemclient.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: systemclient.ChangeStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemclient.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemclient.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/client"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/syncTenantDict",
					Handler: systemtenant.SyncTenantDictHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/syncTenantPackage",
					Handler: systemtenant.SyncTenantPackageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemtenant.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemtenant.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: systemtenant.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: systemtenant.ChangeStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemtenant.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemtenant.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dynamic/clear",
					Handler: systemtenant.ClearHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dynamic/:id",
					Handler: systemtenant.DynamicHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/tenant"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemtenant_package.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemtenant_package.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: systemtenant_package.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: systemtenant_package.ChangeStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemtenant_package.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemtenant_package.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/selectList",
					Handler: systemtenant_package.SelectListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/tenant/package"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/configKey/:code",
					Handler: system_config.ConfigKeyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: system_config.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: system_config.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: system_config.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: system_config.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: system_config.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/config"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/type/:code",
					Handler: systemdictdata.DataByTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemdictdata.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemdictdata.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: systemdictdata.DeleteDictDataHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemdictdata.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemdictdata.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/dict/data"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: systemdict_type.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: systemdict_type.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/refreshCache",
					Handler: systemdict_type.RefreshCacheHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:code",
					Handler: systemdict_type.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: systemdict_type.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: systemdict_type.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/dict/type"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: resourceoss.UploadHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: resourceoss.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: resourceoss.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/resource/oss"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: resourceossconfig.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: resourceossconfig.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: resourceossconfig.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: resourceossconfig.ChangeStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: resourceossconfig.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: resourceossconfig.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/resource/oss/config"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: monitoronline.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: monitoronline.OfflineHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor/online"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/clean",
					Handler: monitoroperLog.CleanHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: monitoroperLog.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: monitoroperLog.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor/operlog"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/clean",
					Handler: monitorlogininfor.CleanHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: monitorlogininfor.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: monitorlogininfor.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor/logininfor"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/cache",
					Handler: monitormonitor.RedisMonitorHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/status",
					Handler: devsse.StatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: devsse.ListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/sendAll",
					Handler: devsse.SendAllHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/send/:id",
					Handler: devsse.SendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/sse"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Sign},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/request",
					Handler: devencrypt.RequestHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/response",
					Handler: devencrypt.ResponseHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/test/api/encrypt"),
	)
}
