// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFbAccountFlowRecord = "fb_account_flow_records"

// FbAccountFlowRecord 账户流水记录表
type FbAccountFlowRecord struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:记录ID" json:"id"`             // 记录ID
	UserID       int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                        // 用户ID
	AccountType  string    `gorm:"column:account_type;not null;default:main;comment:账户类型" json:"account_type"` // 账户类型
	FlowType     string    `gorm:"column:flow_type;comment:交易类型" json:"flow_type"`                             // 交易类型
	BeforeAmount float64   `gorm:"column:before_amount;comment:交易前余额" json:"before_amount"`                    // 交易前余额
	FlowAmount   float64   `gorm:"column:flow_amount;not null;comment:变动金额" json:"flow_amount"`                // 变动金额
	AfterAmount  float64   `gorm:"column:after_amount;comment:交易后余额" json:"after_amount"`                      // 交易后余额
	BusinessNo   string    `gorm:"column:business_no;comment:业务编号" json:"business_no"`                         // 业务编号
	Remark       string    `gorm:"column:remark;comment:备注" json:"remark"`                                     // 备注
	CreatedAt    time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                  // 创建时间
	WalletID     int64     `gorm:"column:wallet_id;comment:钱包ID" json:"wallet_id"`                             // 钱包ID
	Currency     string    `gorm:"column:currency;not null;default:CNY;comment:货币单位" json:"currency"`          // 货币单位
	Description  string    `gorm:"column:description;comment:交易描述" json:"description"`                         // 交易描述
	Status       string    `gorm:"column:status;not null;default:SUCCESS;comment:交易状态" json:"status"`          // 交易状态
	UpdatedAt    time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                           // 更新时间
}

// TableName FbAccountFlowRecord's table name
func (*FbAccountFlowRecord) TableName() string {
	return TableNameFbAccountFlowRecord
}
