// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFbDeviceLoginLog = "fb_device_login_log"

// FbDeviceLoginLog 设备登录日志表
type FbDeviceLoginLog struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	UserID        int64     `gorm:"column:user_id;not null;comment:用户ID，0表示未登录用户" json:"user_id"`                        // 用户ID，0表示未登录用户
	DeviceID      string    `gorm:"column:device_id;not null;comment:设备唯一标识" json:"device_id"`                           // 设备唯一标识
	LoginTime     time.Time `gorm:"column:login_time;not null;default:CURRENT_TIMESTAMP;comment:登录时间" json:"login_time"` // 登录时间
	LoginIP       string    `gorm:"column:login_ip;not null;comment:登录IP" json:"login_ip"`                               // 登录IP
	LoginLocation string    `gorm:"column:login_location;comment:登录地点" json:"login_location"`                            // 登录地点
	LoginType     string    `gorm:"column:login_type;not null;comment:登录方式：PASSWORD/SMS/OTHER" json:"login_type"`        // 登录方式：PASSWORD/SMS/OTHER
	LoginResult   string    `gorm:"column:login_result;not null;comment:登录结果：SUCCESS/FAIL" json:"login_result"`          // 登录结果：SUCCESS/FAIL
	FailReason    string    `gorm:"column:fail_reason;comment:失败原因" json:"fail_reason"`                                  // 失败原因
	RiskLevel     string    `gorm:"column:risk_level;default:LOW;comment:风险等级：LOW/MEDIUM/HIGH" json:"risk_level"`        // 风险等级：LOW/MEDIUM/HIGH
	RiskDetail    string    `gorm:"column:risk_detail;comment:风险详情" json:"risk_detail"`                                  // 风险详情
}

// TableName FbDeviceLoginLog's table name
func (*FbDeviceLoginLog) TableName() string {
	return TableNameFbDeviceLoginLog
}
