// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFbDeposit = "fb_deposits"

// FbDeposit 充值记录表
type FbDeposit struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID        int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                                  // 用户ID
	OrderNo       string    `gorm:"column:order_no;not null;comment:订单号" json:"order_no"`                                                 // 订单号
	Amount        float64   `gorm:"column:amount;not null;comment:充值金额" json:"amount"`                                                    // 充值金额
	Status        string    `gorm:"column:status;not null;comment:状态" json:"status"`                                                      // 状态
	PaymentMethod string    `gorm:"column:payment_method;not null;comment:支付方式" json:"payment_method"`                                    // 支付方式
	PaymentStatus string    `gorm:"column:payment_status;not null;comment:支付状态" json:"payment_status"`                                    // 支付状态
	PaymentNo     string    `gorm:"column:payment_no;comment:第三方支付单号" json:"payment_no"`                                                  // 第三方支付单号
	PaymentTime   time.Time `gorm:"column:payment_time;comment:支付时间" json:"payment_time"`                                                 // 支付时间
	Remark        string    `gorm:"column:remark;comment:备注" json:"remark"`                                                               // 备注
	Currency      string    `gorm:"column:currency;not null;default:CNY;comment:货币类型(CNY或USDT)" json:"currency"`                          // 货币类型(CNY或USDT)
	TargetAccount string    `gorm:"column:target_account;not null;default:MAIN;comment:目标账户类型(MAIN普通钱包或FOREX外汇账户)" json:"target_account"` // 目标账户类型(MAIN普通钱包或FOREX外汇账户)
	Screenshot    string    `gorm:"column:screenshot;comment:充值截图文件路径或ID" json:"screenshot"`                                              // 充值截图文件路径或ID
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName FbDeposit's table name
func (*FbDeposit) TableName() string {
	return TableNameFbDeposit
}
