// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFbFundPosition = "fb_fund_position"

// FbFundPosition 基金用户持仓表
type FbFundPosition struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID         int64     `gorm:"column:user_id;not null" json:"user_id"`
	FundCode       string    `gorm:"column:fund_code;not null;comment:基金代码" json:"fund_code"`                          // 基金代码
	Amount         float64   `gorm:"column:amount;not null;default:0.0000;comment:投入持仓金额" json:"amount"`               // 投入持仓金额
	BuyDate        time.Time `gorm:"column:buy_date;not null;comment:买入日期" json:"buy_date"`                            // 买入日期
	StartDate      time.Time `gorm:"column:start_date;comment:开始计息日" json:"start_date"`                                // 开始计息日
	EndDate        time.Time `gorm:"column:end_date;comment:到期日" json:"end_date"`                                      // 到期日
	Period         int32     `gorm:"column:period;comment:投资周期(天)" json:"period"`                                      // 投资周期(天)
	Rate           float64   `gorm:"column:rate;default:0.00;comment:收益率" json:"rate"`                                 // 收益率
	Profit         float64   `gorm:"column:profit;default:0.00;comment:每天收益(预估)" json:"profit"`                        // 每天收益(预估)
	State          string    `gorm:"column:state;not null;default:PENDING;comment:进行中-ONGOING, 未投入-NONE" json:"state"` // 进行中-ONGOING, 未投入-NONE
	Status         bool      `gorm:"column:status;default:1;comment:状态：0-结束，1-进行中" json:"status"`                      // 状态：0-结束，1-进行中
	CreateTime     time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time" json:"update_time"`
	LastProfitDate time.Time `gorm:"column:last_profit_date;comment:该持仓最后一次收益计算日期(冗余字段)" json:"last_profit_date"` // 该持仓最后一次收益计算日期(冗余字段)
}

// TableName FbFundPosition's table name
func (*FbFundPosition) TableName() string {
	return TableNameFbFundPosition
}
