// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFbIdentityVerify = "fb_identity_verify"

// FbIdentityVerify 实名认证表
type FbIdentityVerify struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                          // 主键ID
	UserID       int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                     // 用户ID
	RealName     string    `gorm:"column:real_name;not null;comment:真实姓名" json:"real_name"`                                 // 真实姓名
	IDCardNo     string    `gorm:"column:id_card_no;not null;comment:身份证号" json:"id_card_no"`                               // 身份证号
	IDCardFront  string    `gorm:"column:id_card_front;comment:身份证正面照片" json:"id_card_front"`                               // 身份证正面照片
	IDCardBack   string    `gorm:"column:id_card_back;comment:身份证反面照片" json:"id_card_back"`                                 // 身份证反面照片
	Status       string    `gorm:"column:status;not null;comment:认证状态：PENDING-待审核 VERIFIED-已通过 REJECTED-已拒绝" json:"status"` // 认证状态：PENDING-待审核 VERIFIED-已通过 REJECTED-已拒绝
	RejectReason string    `gorm:"column:reject_reason;comment:拒绝原因" json:"reject_reason"`                                  // 拒绝原因
	VerifiedAt   time.Time `gorm:"column:verified_at;comment:认证通过/拒绝时间" json:"verified_at"`                                 // 认证通过/拒绝时间
	CreatedAt    time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                               // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                        // 更新时间
}

// TableName FbIdentityVerify's table name
func (*FbIdentityVerify) TableName() string {
	return TableNameFbIdentityVerify
}
