// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFbUser = "fb_users"

// FbUser 用户表
type FbUser struct {
	ID                     int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                                // 用户ID
	Username               string    `gorm:"column:username;not null;comment:用户名" json:"username"`                                          // 用户名
	Password               string    `gorm:"column:password;not null;comment:密码" json:"password"`                                           // 密码
	Email                  string    `gorm:"column:email;comment:邮箱" json:"email"`                                                          // 邮箱
	Mobile                 string    `gorm:"column:mobile;comment:手机号" json:"mobile"`                                                       // 手机号
	Phone                  string    `gorm:"column:phone;comment:手机号" json:"phone"`                                                         // 手机号
	RealName               string    `gorm:"column:real_name;comment:真实姓名" json:"real_name"`                                                // 真实姓名
	IDCard                 string    `gorm:"column:id_card;comment:身份证号" json:"id_card"`                                                    // 身份证号
	VerificationStatus     string    `gorm:"column:verification_status;not null;default:PENDING;comment:实名认证状态" json:"verification_status"` // 实名认证状态
	CreditScore            int32     `gorm:"column:credit_score;default:100;comment:信用分数" json:"credit_score"`                              // 信用分数
	SecurityQuestion       string    `gorm:"column:security_question;comment:密保问题" json:"security_question"`                                // 密保问题
	SecurityAnswer         string    `gorm:"column:security_answer;comment:密保答案" json:"security_answer"`                                    // 密保答案
	Role                   string    `gorm:"column:role;not null;default:USER;comment:用户角色" json:"role"`                                    // 用户角色
	AccountLocked          bool      `gorm:"column:account_locked;not null;comment:账户是否锁定" json:"account_locked"`                           // 账户是否锁定
	FailedAttempts         int32     `gorm:"column:failed_attempts;not null;comment:登录失败次数" json:"failed_attempts"`                         // 登录失败次数
	LastLogin              time.Time `gorm:"column:last_login;comment:最后登录时间" json:"last_login"`                                            // 最后登录时间
	ParentID               int64     `gorm:"column:parent_id;comment:上级代理ID" json:"parent_id"`                                              // 上级代理ID
	Level                  int32     `gorm:"column:level;not null;comment:代理等级" json:"level"`                                               // 代理等级
	AgentLevel             int32     `gorm:"column:agent_level;not null;default:3;comment:团队代理层级：3=仅三级；4=含四级；5=含五级" json:"agent_level"`     // 团队代理层级：3=仅三级；4=含四级；5=含五级
	InviteCode             string    `gorm:"column:invite_code;comment:邀请码" json:"invite_code"`                                             // 邀请码
	CommissionRate         float64   `gorm:"column:commission_rate;default:0.00;comment:佣金比例" json:"commission_rate"`                       // 佣金比例
	TotalCommission        float64   `gorm:"column:total_commission;default:0.00;comment:累计佣金" json:"total_commission"`                     // 累计佣金
	TeamSize               int32     `gorm:"column:team_size;comment:团队规模" json:"team_size"`                                                // 团队规模
	CreatedAt              time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                                     // 创建时间
	UpdatedAt              time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                              // 更新时间
	Status                 string    `gorm:"column:status;comment:用户状态" json:"status"`                                                      // 用户状态
	Verified               bool      `gorm:"column:verified;not null;comment:是否已实名认证：0-未认证 1-已认证" json:"verified"`                          // 是否已实名认证：0-未认证 1-已认证
	PayPassword            string    `gorm:"column:pay_password;comment:交易密码(MD5加密)" json:"pay_password"`                                   // 交易密码(MD5加密)
	PayPasswordUpdatedAt   time.Time `gorm:"column:pay_password_updated_at;comment:交易密码最后更新时间" json:"pay_password_updated_at"`              // 交易密码最后更新时间
	PayPasswordErrorCount  int32     `gorm:"column:pay_password_error_count;comment:交易密码错误次数" json:"pay_password_error_count"`              // 交易密码错误次数
	PayPasswordLockedUntil time.Time `gorm:"column:pay_password_locked_until;comment:交易密码锁定截止时间" json:"pay_password_locked_until"`          // 交易密码锁定截止时间
	Avatar                 string    `gorm:"column:avatar;comment:用户头像(base64)" json:"avatar"`                                              // 用户头像(base64)
	ContractControl        int32     `gorm:"column:contract_control;default:3;comment:合约控制 1 = 赢  2 = 输  3 = 自然" json:"contract_control"`   // 合约控制 1 = 赢  2 = 输  3 = 自然
	IsOnline               string    `gorm:"column:is_online;not null;default:0" json:"is_online"`
	Remark                 string    `gorm:"column:remark;comment:说明" json:"remark"`                          // 说明
	Flag                   int32     `gorm:"column:flag;not null;comment:0正常1删除" json:"flag"`                 // 0正常1删除
	IsTest                 bool      `gorm:"column:is_test;not null;comment:是否测试账号：0-正式 1-测试" json:"is_test"` // 是否测试账号：0-正式 1-测试
}

// TableName FbUser's table name
func (*FbUser) TableName() string {
	return TableNameFbUser
}
