// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFbUserWallet = "fb_user_wallets"

// FbUserWallet 用户钱包表
type FbUserWallet struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:钱包ID" json:"id"`                                                 // 钱包ID
	UserID       int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                                            // 用户ID
	AccountType  string    `gorm:"column:account_type;not null;default:STOCK;comment:账户类型：STOCK-股票账户，FOREX-外汇账户，FUTURES-期货账户" json:"account_type"` // 账户类型：STOCK-股票账户，FOREX-外汇账户，FUTURES-期货账户
	Balance      float64   `gorm:"column:balance;not null;default:0.00;comment:余额" json:"balance"`                                                 // 余额
	FrozenAmount float64   `gorm:"column:frozen_amount;not null;default:0.00;comment:冻结金额" json:"frozen_amount"`                                   // 冻结金额
	Frozen       bool      `gorm:"column:frozen;not null;comment:是否冻结" json:"frozen"`                                                              // 是否冻结
	CreatedAt    time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                                                      // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                                                      // 更新时间
	Version      int64     `gorm:"column:version;not null;comment:版本号" json:"version"`                                                             // 版本号
	Currency     string    `gorm:"column:currency;not null;default:CNY;comment:种类" json:"currency"`                                                // 种类
	DrawTicket   int32     `gorm:"column:draw_ticket;not null;comment:抽奖券数量" json:"draw_ticket"`                                                   // 抽奖券数量
}

// TableName FbUserWallet's table name
func (*FbUserWallet) TableName() string {
	return TableNameFbUserWallet
}
