// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFbWithdraw = "fb_withdraws"

// FbWithdraw 提现记录表
type FbWithdraw struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID        int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`               // 用户ID
	OrderNo       string    `gorm:"column:order_no;not null;comment:订单号" json:"order_no"`              // 订单号
	Amount        float64   `gorm:"column:amount;not null;comment:提现金额" json:"amount"`                 // 提现金额
	Status        string    `gorm:"column:status;not null;comment:状态" json:"status"`                   // 状态
	BankName      string    `gorm:"column:bank_name;not null;comment:银行名称" json:"bank_name"`           // 银行名称
	BankCardNo    string    `gorm:"column:bank_card_no;not null;comment:银行卡号" json:"bank_card_no"`     // 银行卡号
	AccountName   string    `gorm:"column:account_name;not null;comment:开户名" json:"account_name"`      // 开户名
	PaymentStatus string    `gorm:"column:payment_status;not null;comment:支付状态" json:"payment_status"` // 支付状态
	PaymentNo     string    `gorm:"column:payment_no;comment:银行转账流水号" json:"payment_no"`               // 银行转账流水号
	PaymentTime   time.Time `gorm:"column:payment_time;comment:支付时间" json:"payment_time"`              // 支付时间
	Remark        string    `gorm:"column:remark;comment:备注" json:"remark"`                            // 备注
	RejectReason  string    `gorm:"column:reject_reason;comment:拒绝原因" json:"reject_reason"`            // 拒绝原因
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	WithdrawType  string    `gorm:"column:withdraw_type;not null;default:CNY" json:"withdraw_type"`
}

// TableName FbWithdraw's table name
func (*FbWithdraw) TableName() string {
	return TableNameFbWithdraw
}
