// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/plugin/soft_delete"
	"time"
)

const TableNameSysTenantPackage = "sys_tenant_package"

// SysTenantPackage 租户套餐表
type SysTenantPackage struct {
	PackageID         string                `gorm:"column:package_id;primaryKey;comment:租户套餐id" json:"package_id"`                        // 租户套餐id
	PackageName       string                `gorm:"column:package_name;comment:套餐名称" json:"package_name"`                                 // 套餐名称
	MenuIds           string                `gorm:"column:menu_ids;comment:关联菜单id" json:"menu_ids"`                                       // 关联菜单id
	Remark            string                `gorm:"column:remark;comment:备注" json:"remark"`                                               // 备注
	MenuCheckStrictly bool                  `gorm:"column:menu_check_strictly;default:1;comment:菜单树选择项是否关联显示" json:"menu_check_strictly"` // 菜单树选择项是否关联显示
	Status            string                `gorm:"column:status;default:0;comment:状态（0正常 1停用）" json:"status"`                            // 状态（0正常 1停用）
	DelFlag           soft_delete.DeletedAt `gorm:"softDelete:flag"`
	CreateDept        int64                 `gorm:"column:create_dept;comment:创建部门" json:"create_dept"` // 创建部门
	CreateBy          int64                 `gorm:"column:create_by;comment:创建者" json:"create_by"`      // 创建者
	CreateTime        time.Time             `gorm:"column:create_time;comment:创建时间" json:"create_time"` // 创建时间
	UpdateBy          int64                 `gorm:"column:update_by;comment:更新者" json:"update_by"`      // 更新者
	UpdateTime        time.Time             `gorm:"column:update_time;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName SysTenantPackage's table name
func (*SysTenantPackage) TableName() string {
	return TableNameSysTenantPackage
}
