// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/plugin/soft_delete"
	"time"
)

const TableNameSysClient = "sys_client"

// SysClient 系统授权表
type SysClient struct {
	ID            string                `gorm:"column:id;primaryKey;comment:id" json:"id"`                                    // id
	ClientID      string                `gorm:"column:client_id;comment:客户端id" json:"client_id"`                              // 客户端id
	ClientKey     string                `gorm:"column:client_key;comment:客户端key" json:"client_key"`                           // 客户端key
	ClientSecret  string                `gorm:"column:client_secret;comment:客户端秘钥" json:"client_secret"`                      // 客户端秘钥
	GrantType     string                `gorm:"column:grant_type;comment:授权类型" json:"grant_type"`                             // 授权类型
	DeviceType    string                `gorm:"column:device_type;comment:设备类型" json:"device_type"`                           // 设备类型
	ActiveTimeout int32                 `gorm:"column:active_timeout;default:1800;comment:token活跃超时时间" json:"active_timeout"` // token活跃超时时间
	Timeout       int32                 `gorm:"column:timeout;default:604800;comment:token固定超时" json:"timeout"`               // token固定超时
	Status        string                `gorm:"column:status;default:0;comment:状态（0正常 1停用）" json:"status"`                    // 状态（0正常 1停用）
	DelFlag       soft_delete.DeletedAt `gorm:"softDelete:flag"`
	CreateDept    int64                 `gorm:"column:create_dept;comment:创建部门" json:"create_dept"` // 创建部门
	CreateBy      int64                 `gorm:"column:create_by;comment:创建者" json:"create_by"`      // 创建者
	CreateTime    time.Time             `gorm:"column:create_time;comment:创建时间" json:"create_time"` // 创建时间
	UpdateBy      int64                 `gorm:"column:update_by;comment:更新者" json:"update_by"`      // 更新者
	UpdateTime    time.Time             `gorm:"column:update_time;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName SysClient's table name
func (*SysClient) TableName() string {
	return TableNameSysClient
}
