// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.0

package types

type HealthResp struct {
	Status string `json:"status"`
}

type AddOrUpdateUserReq struct {
	RoleIds []string `json:"roleIds,optional"`
	PostIds []string `json:"postIds,optional"`
	UserBase
}

type UpdateUserStatusReq struct {
	UserId string `json:"userId"`
	Status string `json:"status"`
}

type UserDetailResp struct {
	PostIds []string    `json:"postIds"`
	Posts   []*PostBase `json:"posts"`
	RoleIds []string    `json:"roleIds"`
	Roles   []*RoleBase `json:"roles"`
	User    *UserRoles  `json:"user"`
}

type UserQuery struct {
	UserId      string `form:"userId,optional"`
	TenantId    string `form:"tenantId,optional"`
	DeptId      string `form:"deptId,optional"`
	UserName    string `form:"userName,optional"`
	NickName    string `form:"nickName,optional"`
	UserType    string `form:"userType,optional"`
	Email       string `form:"email,optional"`
	PhoneNumber string `form:"phonenumber,optional"`
	Sex         string `form:"sex,optional"`
	Avatar      int64  `form:"avatar,optional"`
	Status      string `form:"status,optional"`
	DelFlag     string `form:"delFlag,optional"`
	LoginIp     string `form:"loginIp,optional"`
}

type QueryPageUserListReq struct {
	PageReq
	UserQuery
}

type QueryPageUserListResp struct {
	Total int64             `json:"total"`
	Rows  []UserAndDeptName `json:"rows"`
}

type UserAndDeptName struct {
	UserRoles
	DeptName   string `json:"deptName"`
	CreateTime string `json:"createTime"`
}

type QueryUserListReq struct {
	UserQuery
}

type UserInfoResp struct {
	User        UserRoles `json:"user"`
	Roles       []string  `json:"roles"`
	Permissions []string  `json:"permissions"`
}

type UserRoles struct {
	UserBase
	Roles []RoleBase `json:"roles,omitempty"`
}

type ResetPwdReq struct {
	UserId   string `json:"userId"`
	Password string `json:"password"`
}

type UserProfileResp struct {
	User      UserAndDeptName `json:"user"`
	PostGroup string          `json:"postGroup"`
	RoleGroup string          `json:"roleGroup"`
}

type PageReq struct {
	PageNum  int64 `form:"pageNum,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
	TimeReq
}

type IdReq struct {
	Id string `path:"id"`
}

type CodeReq struct {
	Code string `path:"code"`
}

type IdsReq struct {
	Ids string `path:"ids"`
}

type TimeReq struct {
	BeginTime string `form:"params[beginTime],optional"`
	EndTime   string `form:"params[endTime],optional"`
}

type UserBase struct {
	UserID      string `json:"userId,optional"`
	TenantID    string `json:"tenantId,optional"`
	DeptID      string `json:"deptId,optional"`
	UserName    string `json:"userName"`
	NickName    string `json:"nickName"`
	UserType    string `json:"userType,optional"`
	Email       string `json:"email,optional"`
	PhoneNumber string `json:"phonenumber,optional"`
	Sex         string `json:"sex,optional"`
	Avatar      string `json:"avatar,optional"`
	Password    string `json:"password,optional"`
	Status      string `json:"status,optional"`
	LoginIp     string `json:"loginIp,optional"`
	LoginDate   string `json:"loginDate,optional"`
	Remark      string `json:"remark,optional"`
}

type UserRoleBase struct {
	UserID string `json:"userId"`
	RoleID string `json:"roleId"`
}

type RoleBase struct {
	RoleID            string `json:"roleId,optional"`
	TenantID          string `json:"tenantId,optional"`
	RoleName          string `json:"roleName"`
	RoleKey           string `json:"roleKey"`
	RoleSort          int32  `json:"roleSort"`
	DataScope         string `json:"dataScope,optional"`
	MenuCheckStrictly bool   `json:"menuCheckStrictly,optional"`
	DeptCheckStrictly bool   `json:"deptCheckStrictly,optional"`
	Status            string `json:"status,default=0,optional"`
	Remark            string `json:"remark,optional"`
	CreateTime        string `json:"createTime,optional"`
	SuperAdmin        bool   `json:"superAdmin,omitempty,optional"`
}

type UserPostBase struct {
	UserID string `json:"userId"`
	PostID string `json:"postId"`
}

type PostBase struct {
	PostID       string `json:"postId,optional"`
	TenantID     string `json:"tenantId,optional"`
	DeptID       string `json:"deptId"`
	PostCode     string `json:"postCode"`
	PostCategory string `json:"postCategory,optional"`
	PostName     string `json:"postName"`
	PostSort     int32  `json:"postSort"`
	Status       string `json:"status,default=0"`
	Remark       string `json:"remark,optional"`
	CreateTime   string `json:"createTime,optional"`
}

type RoleMenuBase struct {
	RoleID string `json:"roleId"`
	MenuID string `json:"menuId"`
}

type MenuBase struct {
	MenuID     string `json:"menuId,optional"`
	MenuName   string `json:"menuName"`
	ParentID   string `json:"parentId,optional"`
	OrderNum   int32  `json:"orderNum,optional"`
	Path       string `json:"path,optional"`
	Component  string `json:"component,optional"`
	QueryParam string `json:"queryParam,optional"`
	IsFrame    string `json:"isFrame,optional"`
	IsCache    string `json:"isCache,optional"`
	MenuType   string `json:"menuType,optional"`
	Visible    string `json:"visible,optional"`
	Status     string `json:"status,optional"`
	Perms      string `json:"perms,optional"`
	Icon       string `json:"icon,optional"`
	Remark     string `json:"remark,optional"`
	CreateTime string `json:"createTime,optional"`
}

type RoleDeptBase struct {
	RoleID string `json:"roleId"`
	DeptID string `json:"deptId"`
}

type DeptBase struct {
	DeptID       string      `json:"deptId,optional"`
	TenantID     string      `json:"tenantId,optional"`
	ParentID     string      `json:"parentId,optional"`
	Ancestors    string      `json:"ancestors,optional"`
	DeptName     string      `json:"deptName,optional"`
	DeptCategory string      `json:"deptCategory,optional"`
	OrderNum     int32       `json:"orderNum,optional"`
	Leader       *string     `json:"leader,optional"`
	Phone        string      `json:"phone,optional"`
	Email        string      `json:"email,optional"`
	Status       string      `json:"status,optional"`
	CreateTime   string      `json:"createTime,optional"`
	Children     []*DeptBase `json:"children,optional,omitempty"`
}

type DictDataBase struct {
	DictCode   string `json:"dictCode,optional"`
	TenantId   string `json:"tenantId,optional"`
	DictSort   int32  `json:"dictSort,optional"`
	DictLabel  string `json:"dictLabel,optional"`
	DictValue  string `json:"dictValue,optional"`
	DictType   string `json:"dictType,optional"`
	CssClass   string `json:"cssClass,optional"`
	ListClass  string `json:"listClass,optional"`
	IsDefault  string `json:"isDefault,optional"`
	CreateTime string `json:"createTime,optional"`
	Remark     string `json:"remark,optional"`
}

type DictTypeBase struct {
	DictID     string `json:"dictId,optional"`
	TenantID   string `json:"tenantId,optional"`
	DictName   string `json:"dictName,optional"`
	DictType   string `json:"dictType,optional"`
	CreateTime string `json:"createTime,optional"`
	Remark     string `json:"remark,optional"`
}

type ConfigBase struct {
	ConfigID    string `json:"configId,optional"`
	TenantID    string `json:"tenantId,optional"`
	ConfigName  string `json:"configName,optional"`
	ConfigKey   string `json:"configKey,optional"`
	ConfigValue string `json:"configValue,optional"`
	ConfigType  string `json:"configType,optional"`
	Remark      string `json:"remark,optional"`
	CreateTime  string `json:"createTime,optional"`
}

type NoticeBase struct {
	NoticeID      string `json:"noticeId,optional"`
	TenantID      string `json:"tenantId,optional"`
	NoticeTitle   string `json:"noticeTitle"`
	NoticeType    string `json:"noticeType"`
	NoticeContent string `json:"noticeContent,optional"`
	Status        string `json:"status,optional"`
	Remark        string `json:"remark,optional"`
	CreateTime    string `json:"createTime,optional,omitempty"`
	CreateByName  string `json:"createByName,optional,omitempty"`
}

type TenantBase struct {
	ID              string `json:"id,optional"`
	TenantID        string `json:"tenantId,optional"`
	ContactUserName string `json:"contactUserName,optional"`
	ContactPhone    string `json:"contactPhone,optional"`
	CompanyName     string `json:"companyName,optional"`
	LicenseNumber   string `json:"licenseNumber,optional"`
	Address         string `json:"address,optional"`
	Intro           string `json:"intro,optional"`
	Domain          string `json:"domain,optional"`
	Remark          string `json:"remark,optional"`
	PackageId       string `json:"packageId,optional"`
	ExpireTime      string `json:"expireTime,optional"`
	AccountCount    int32  `json:"accountCount,optional"`
	Status          string `json:"status,optional"`
}

type TenantPackageBase struct {
	PackageID         string `json:"packageId,optional"`
	PackageName       string `json:"packageName,optional"`
	MenuIds           string `json:"menuIds,optional"`
	Remark            string `json:"remark,optional"`
	MenuCheckStrictly bool   `json:"menuCheckStrictly,optional"`
	Status            string `json:"status,optional"`
}

type ClientBase struct {
	ID            string   `json:"id,optional"`
	ClientID      string   `json:"clientId,optional"`
	ClientKey     string   `json:"clientKey,optional"`
	ClientSecret  string   `json:"clientSecret,optional"`
	GrantType     string   `json:"grantType,optional"`
	GrantTypeList []string `json:"grantTypeList,optional"`
	DeviceType    string   `json:"deviceType,optional"`
	ActiveTimeout int32    `json:"activeTimeout,optional"`
	Timeout       int32    `json:"timeout,optional"`
	Status        string   `json:"status,optional"`
}

type SocialBase struct {
	ID               string `json:"id,optional"`
	UserID           string `json:"userId"`
	TenantID         string `json:"tenantId,optional"`
	AuthID           string `json:"authId"`
	Source           string `json:"source"`
	OpenID           string `json:"openId,optional"`
	UserName         string `json:"userName"`
	NickName         string `json:"nickName,optional"`
	Email            string `json:"email,optional"`
	Avatar           string `json:"avatar,optional"`
	AccessToken      string `json:"accessToken"`
	ExpireIn         int32  `json:"expireIn,optional"`
	RefreshToken     string `json:"refreshToken,optional"`
	AccessCode       string `json:"accessCode,optional"`
	UnionId          string `json:"unionId,optional"`
	Scope            string `json:"scope,optional"`
	TokenType        string `json:"tokenType,optional"`
	IdToken          string `json:"idToken,optional"`
	MacAlgorithm     string `json:"macAlgorithm,optional"`
	MacKey           string `json:"macKey,optional"`
	Code             string `json:"code,optional"`
	OauthToken       string `json:"oauthToken,optional"`
	OauthTokenSecret string `json:"oauthTokenSecret,optional"`
}

type DeptTree struct {
	Disabled bool       `json:"disabled"`
	Id       string     `json:"id"`
	Label    string     `json:"label"`
	ParentId string     `json:"parentId"`
	Weight   int64      `json:"weight"`
	Children []DeptTree `json:"children"`
}

type LogininforBase struct {
	InfoId        string `json:"infoId,optional"`        // 访问ID
	TenantId      string `json:"tenantId,optional"`      // 租户编号
	UserName      string `json:"userName,optional"`      // 用户账号
	ClientKey     string `json:"clientKey,optional"`     // 客户端
	DeviceType    string `json:"deviceType,optional"`    // 设备类型
	Ipaddr        string `json:"ipaddr,optional"`        // 登录IP地址
	LoginLocation string `json:"loginLocation,optional"` // 登录地点
	Browser       string `json:"browser,optional"`       // 浏览器类型
	Os            string `json:"os,optional"`            // 操作系统
	Status        string `json:"status,optional"`        // 登录状态（0成功 1失败）
	Msg           string `json:"msg,optional"`           // 提示消息
	LoginTime     string `json:"loginTime,optional"`     // 访问时间
}

type OperLogBase struct {
	OperId        string `json:"operId,optional"`        // 日志主键
	TenantId      string `json:"tenantId,optional"`      // 租户编号
	Title         string `json:"title,optional"`         // 模块标题
	BusinessType  int32  `json:"businessType,optional"`  // 业务类型（0其它 1新增 2修改 3删除）
	Method        string `json:"method,optional"`        // 方法名称
	RequestMethod string `json:"requestMethod,optional"` // 请求方式
	OperatorType  int32  `json:"operatorType,optional"`  // 操作类别（0其它 1后台用户 2手机端用户）
	OperName      string `json:"operName,optional"`      // 操作人员
	DeptName      string `json:"deptName,optional"`      // 部门名称
	OperUrl       string `json:"operUrl,optional"`       // 请求URL
	OperIp        string `json:"operIp,optional"`        // 主机地址
	OperLocation  string `json:"operLocation,optional"`  // 操作地点
	OperParam     string `json:"operParam,optional"`     // 请求参数
	JsonResult    string `json:"jsonResult,optional"`    // 返回参数
	Status        int32  `json:"status,optional"`        // 操作状态（0正常 1异常）
	ErrorMsg      string `json:"errorMsg,optional"`      // 错误消息
	OperTime      string `json:"operTime,optional"`      // 操作时间
	CostTime      int64  `json:"costTime,optional"`      // 消耗时间
}

type OssBase struct {
	OssId        string `json:"ossId,optional"`        // 对象存储主键
	TenantId     string `json:"tenantId,optional"`     // 租户编号
	FileName     string `json:"fileName,optional"`     // 文件名
	OriginalName string `json:"originalName,optional"` // 原名
	FileSuffix   string `json:"fileSuffix,optional"`   // 文件后缀名
	Url          string `json:"url,optional"`          // URL地址
	Ext1         string `json:"ext1,optional"`         // 扩展字段
	CreateDept   int64  `json:"createDept,optional"`   // 创建部门
	CreateTime   string `json:"createTime,optional"`   // 创建时间
	CreateBy     int64  `json:"createBy,optional"`     // 上传人
	UpdateTime   string `json:"updateTime,optional"`   // 更新时间
	UpdateBy     int64  `json:"updateBy,optional"`     // 更新人
	Service      string `json:"service,optional"`      // 服务商
}

type OssConfigBase struct {
	OssConfigID  string `json:"ossConfigId,optional"`  // 主键
	TenantId     string `json:"tenantId,optional"`     // 租户编号
	ConfigKey    string `json:"configKey,optional"`    // 配置key
	AccessKey    string `json:"accessKey,optional"`    // accessKey
	SecretKey    string `json:"secretKey,optional"`    // 秘钥
	BucketName   string `json:"bucketName,optional"`   // 桶名称
	Prefix       string `json:"prefix,optional"`       // 前缀
	Endpoint     string `json:"endpoint,optional"`     // 访问站点
	Domain       string `json:"domain,optional"`       // 自定义域名
	IsHTTPS      string `json:"isHttps,optional"`      // 是否https（Y=是,N=否）
	Region       string `json:"region,optional"`       // 域
	AccessPolicy string `json:"accessPolicy,optional"` // 桶权限类型(0=private 1=public 2=custom)
	Status       string `json:"status,optional"`       // 是否默认（0=是,1=否）
	Ext1         string `json:"ext1,optional"`         // 扩展字段
	CreateDept   int64  `json:"createDept,optional"`   // 创建部门
	CreateBy     int64  `json:"createBy,optional"`     // 创建者
	CreateTime   string `json:"createTime,optional"`   // 创建时间
	UpdateBy     int64  `json:"updateBy,optional"`     // 更新者
	UpdateTime   string `json:"updateTime,optional"`   // 更新时间
	Remark       string `json:"remark,optional"`       // 备注
}

type AddOrUpdateRoleReq struct {
	RoleBase
	MenuIds []string `json:"menuIds"`
}

type UpdateRoleStatusReq struct {
	RoleID string `json:"roleId"`
	Status string `json:"status,default=0"` //角色状态（0正常 1停用）
}

type RoleDetailResp struct {
	RoleBase
	CreateDept int64  `json:"createDept"` //创建部门
	CreateBy   int64  `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	UpdateBy   int64  `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
	Remark     string `json:"remark"`     //备注
}

type RoleQuery struct {
	RoleId            string `form:"roleId,optional"`            //角色ID
	TenantId          string `form:"tenantId,optional"`          //租户编号
	RoleName          string `form:"roleName,optional"`          //角色名称
	RoleKey           string `form:"roleKey,optional"`           //角色权限字符串
	RoleSort          int32  `form:"roleSort,optional"`          //显示顺序
	DataScope         string `form:"dataScope,optional"`         //数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限 5：仅本人数据权限 6：部门及以下或本人数据权限）
	MenuCheckStrictly int32  `form:"menuCheckStrictly,optional"` //菜单树选择项是否关联显示
	DeptCheckStrictly int32  `form:"deptCheckStrictly,optional"` //部门树选择项是否关联显示
	Status            string `form:"status,optional"`            //角色状态（0正常 1停用）
}

type RolePageSetReq struct {
	PageReq
	RoleQuery
}

type RolePageSetResp struct {
	Total int64      `json:"total"`
	Rows  []RoleBase `json:"rows"`
}

type DeptTreeResp struct {
	CheckedKeys []string   `json:"checkedKeys"`
	Depts       []DeptTree `json:"depts"`
}

type AllocatedReq struct {
	PageReq
	RoleId      string `form:"roleId"`
	UserName    string `form:"userName,optional"`
	PhoneNumber string `form:"phonenumber,optional"`
}

type AllocatedResp struct {
	Total int64      `json:"total"`
	Rows  []UserBase `json:"rows"`
}

type SelectAllReq struct {
	RoleId  string `form:"roleId"`
	UserIds string `form:"userIds"`
}

type CancelReq struct {
	RoleId string `json:"roleId"`
	UserId string `json:"userId"`
}

type ModifyDeptReq struct {
	DeptBase
}

type DeptQuery struct {
	DeptId       string `form:"deptId,optional"`       // 部门ID
	TenantId     string `form:"tenantId,optional"`     // 租户编号
	ParentId     string `form:"parentId,optional"`     // 父部门ID
	Ancestors    string `form:"ancestors,optional"`    // 祖级列表
	DeptName     string `form:"deptName,optional"`     // 部门名称
	DeptCategory string `form:"deptCategory,optional"` // 部门类别编码
	OrderNum     int32  `form:"orderNum,optional"`     // 显示顺序
	Leader       int64  `form:"leader,optional"`       // 负责人
	Phone        string `form:"phone,optional"`        // 联系电话
	Email        string `form:"email,optional"`        // 邮箱
	Status       string `form:"status,optional"`       // 部门状态（0正常 1停用）
	DelFlag      string `form:"delFlag,optional"`      // 删除标志（0代表存在 1代表删除）
	CreateDept   int64  `form:"createDept,optional"`   // 创建部门
	CreateBy     int64  `form:"createBy,optional"`     // 创建者
	CreateTime   string `form:"createTime,optional"`   // 创建时间
	UpdateBy     int64  `form:"updateBy,optional"`     // 更新者
	UpdateTime   string `form:"updateTime,optional"`   // 更新时间
}

type PageSetDeptResp struct {
	Total int64      `json:"total"`
	Rows  []DeptBase `json:"rows"`
}

type ModifyMenuReq struct {
	MenuBase
}

type MenuQuery struct {
	MenuId     string `form:"menuId,optional"`     // 菜单ID
	MenuName   string `form:"menuName,optional"`   // 菜单名称
	ParentId   string `form:"parentId,optional"`   // 父菜单ID
	OrderNum   int32  `form:"orderNum,optional"`   // 显示顺序
	Path       string `form:"path,optional"`       // 路由地址
	Component  string `form:"component,optional"`  // 组件路径
	QueryParam string `form:"queryParam,optional"` // 路由参数
	IsFrame    int32  `form:"isFrame,optional"`    // 是否为外链（0是 1否）
	IsCache    int32  `form:"isCache,optional"`    // 是否缓存（0缓存 1不缓存）
	MenuType   string `form:"menuType,optional"`   // 菜单类型（M目录 C菜单 F按钮）
	Visible    string `form:"visible,optional"`    // 显示状态（0显示 1隐藏）
	Status     string `form:"status,optional"`     // 菜单状态（0正常 1停用）
	Perms      string `form:"perms,optional"`      // 权限标识
}

type QueryMenuListReq struct {
	MenuQuery
}

type MenuDetailResp struct {
	MenuBase
	CreateDept int64  `json:"createDept"`
	CreateBy   int64  `json:"createBy"`
	CreateTime string `json:"createTime"`
	UpdateBy   int64  `json:"updateBy"`
	UpdateTime string `json:"updateTime"`
}

type RouterMenuResp struct {
	MenuId     string            `json:"menuId"`
	Name       string            `json:"name"`
	Path       string            `json:"path"`
	Hidden     bool              `json:"hidden"`
	Redirect   string            `json:"redirect,optional"` // 可选
	Component  string            `json:"component"`
	AlwaysShow bool              `json:"alwaysShow,optional"` // 可选
	Meta       *RouterMenuMeta   `json:"meta"`
	ParentId   string            `json:"parentId"`
	Children   []*RouterMenuResp `json:"children,omitempty"`
}

type RouterMenuMeta struct {
	Title   string `json:"title"`
	Icon    string `json:"icon"`
	NoCache bool   `json:"noCache"`
	Link    string `json:"link,optional"`
}

type SelectMenuTreeResp struct {
	CheckedKeys []string          `json:"checkedKeys"`
	Menus       []*SelectMenuTree `json:"menus"`
}

type SelectMenuTree struct {
	Id       string            `json:"id"`
	ParentId string            `json:"parentId"`
	MenuType string            `json:"menuType"`
	Icon     string            `json:"icon"`
	Weight   int32             `json:"weight"`
	Label    string            `json:"label"`
	Children []*SelectMenuTree `json:"children,omitempty"`
}

type ModifyPostReq struct {
	PostBase
}

type PostQuery struct {
	PostId       string `form:"postId,optional"`       // 岗位ID
	TenantId     string `form:"tenantId,optional"`     // 租户编号
	DeptId       string `form:"deptId,optional"`       // 部门ID
	PostCode     string `form:"postCode,optional"`     // 岗位编码
	PostCategory string `form:"postCategory,optional"` // 岗位类别编码
	PostName     string `form:"postName,optional"`     // 岗位名称
	PostSort     int32  `form:"postSort,optional"`     // 显示顺序
	Status       string `form:"status,optional"`       // 状态（0正常 1停用）
	CreateDept   int64  `form:"createDept,optional"`   // 创建部门
	CreateBy     int64  `form:"createBy,optional"`     // 创建者
	CreateTime   string `form:"createTime,optional"`   // 创建时间
	UpdateBy     int64  `form:"updateBy,optional"`     // 更新者
	UpdateTime   string `form:"updateTime,optional"`   // 更新时间
	Remark       string `form:"remark,optional"`       // 备注
}

type PageSetRoleReq struct {
	PageReq
	PostQuery
	BelongDeptId string `form:"belongDeptId, optional"`
}

type PageSetRoleResp struct {
	Total int64       `json:"total"`
	Rows  []*PostBase `json:"rows"`
}

type ModifyNoticeReq struct {
	NoticeBase
}

type NoticeQuery struct {
	NoticeId      string `form:"noticeId,optional"`      // 公告ID
	TenantId      string `form:"tenantId,optional"`      // 租户编号
	NoticeTitle   string `form:"noticeTitle,optional"`   // 公告标题
	NoticeType    string `form:"noticeType,optional"`    // 公告类型（1通知 2公告）
	NoticeContent string `form:"noticeContent,optional"` // 公告内容
	Status        string `form:"status,optional"`        // 公告状态（0正常 1关闭）
	CreateDept    int64  `form:"createDept,optional"`    // 创建部门
	CreateBy      string `form:"createBy,optional"`      // 创建者
	CreateTime    string `form:"createTime,optional"`    // 创建时间
	UpdateBy      int64  `form:"updateBy,optional"`      // 更新者
	UpdateTime    string `form:"updateTime,optional"`    // 更新时间
	Remark        string `form:"remark,optional"`        // 备注
}

type PageSetNoticeReq struct {
	PageReq
	NoticeQuery
}

type PageSetNoticeResp struct {
	Rows  []*NoticeBase `json:"rows"`
	Total int64         `json:"total"`
}

type ModifyClientReq struct {
	ClientBase
}

type ClientQuery struct {
	Id            string `form:"id,optional"`            // id
	ClientId      string `form:"clientId,optional"`      // 客户端id
	ClientKey     string `form:"clientKey,optional"`     // 客户端key
	ClientSecret  string `form:"clientSecret,optional"`  // 客户端秘钥
	GrantType     string `form:"grantType,optional"`     // 授权类型
	DeviceType    string `form:"deviceType,optional"`    // 设备类型
	ActiveTimeout int32  `form:"activeTimeout,optional"` // token活跃超时时间
	Timeout       int32  `form:"timeout,optional"`       // token固定超时
	Status        string `form:"status,optional"`        // 状态（0正常 1停用）
	DelFlag       string `form:"delFlag,optional"`       // 删除标志（0代表存在 1代表删除）
	CreateDept    int64  `form:"createDept,optional"`    // 创建部门
	CreateBy      int64  `form:"createBy,optional"`      // 创建者
	CreateTime    string `form:"createTime,optional"`    // 创建时间
	UpdateBy      int64  `form:"updateBy,optional"`      // 更新者
	UpdateTime    string `form:"updateTime,optional"`    // 更新时间
}

type PageSetClientReq struct {
	PageReq
	ClientQuery
}

type PageSetClientResp struct {
	Rows  []*ClientBase `json:"rows"`
	Total int64         `json:"total"`
}

type ChangeStatusClientReq struct {
	ClientID string `json:"clientId"`
	Status   string `json:"status"`
}

type ModifyTenantReq struct {
	TenantBase
	UserName string `json:"username,optional"`
	Password string `json:"password,optional"`
}

type TenantQuery struct {
	Id              string `form:"id,optional"`              // id
	TenantId        string `form:"tenantId,optional"`        // 租户编号
	ContactUserName string `form:"contactUserName,optional"` // 联系人
	ContactPhone    string `form:"contactPhone,optional"`    // 联系电话
	CompanyName     string `form:"companyName,optional"`     // 企业名称
	LicenseNumber   string `form:"licenseNumber,optional"`   // 统一社会信用代码
	Address         string `form:"address,optional"`         // 地址
	Intro           string `form:"intro,optional"`           // 企业简介
	Domain          string `form:"domain,optional"`          // 域名
	Remark          string `form:"remark,optional"`          // 备注
	PackageId       int64  `form:"packageId,optional"`       // 租户套餐编号
	ExpireTime      string `form:"expireTime,optional"`      // 过期时间
	AccountCount    int32  `form:"accountCount,optional"`    // 用户数量（-1不限制）
	Status          string `form:"status,optional"`          // 租户状态（0正常 1停用）
	DelFlag         string `form:"delFlag,optional"`         // 删除标志（0代表存在 1代表删除）
	CreateDept      int64  `form:"createDept,optional"`      // 创建部门
	CreateBy        int64  `form:"createBy,optional"`        // 创建者
	CreateTime      string `form:"createTime,optional"`      // 创建时间
	UpdateBy        int64  `form:"updateBy,optional"`        // 更新者
	UpdateTime      string `form:"updateTime,optional"`      // 更新时间
}

type PageSetTenantReq struct {
	PageReq
	TenantQuery
}

type PageSetTenantResp struct {
	Rows  []*TenantBase `json:"rows"`
	Total int64         `json:"total"`
}

type SyncTenantPackageReq struct {
	TenantId  string `form:"tenantId"`
	PackageId string `form:"packageId"`
}

type ChangeStatusTenantReq struct {
	Id       string `json:"id"`
	Status   string `json:"status"`
	TenantId string `json:"tenantId"`
}

type ModifyTenantPackageReq struct {
	PackageID         string   `json:"packageId,optional"`
	PackageName       string   `json:"packageName,optional"`
	MenuIds           []string `json:"menuIds,optional"`
	Remark            string   `json:"remark,optional"`
	MenuCheckStrictly bool     `json:"menuCheckStrictly,optional"`
}

type TenantPackageQuery struct {
	PackageId         string `form:"packageId,optional"`         // 租户套餐id
	PackageName       string `form:"packageName,optional"`       // 套餐名称
	MenuIds           string `form:"menuIds,optional"`           // 关联菜单id
	Remark            string `form:"remark,optional"`            // 备注
	MenuCheckStrictly bool   `form:"menuCheckStrictly,optional"` // 菜单树选择项是否关联显示
	Status            string `form:"status,optional"`            // 状态（0正常 1停用）
	DelFlag           string `form:"delFlag,optional"`           // 删除标志（0代表存在 1代表删除）
	CreateDept        int64  `form:"createDept,optional"`        // 创建部门
	CreateBy          int64  `form:"createBy,optional"`          // 创建者
	CreateTime        string `form:"createTime,optional"`        // 创建时间
	UpdateBy          int64  `form:"updateBy,optional"`          // 更新者
	UpdateTime        string `form:"updateTime,optional"`        // 更新时间
}

type PageSetTenantPackageReq struct {
	PageReq
	TenantPackageQuery
}

type PageSetTenantPackageResp struct {
	Rows  []*TenantPackageBase `json:"rows"`
	Total int64                `json:"total"`
}

type ChangeStatusTenantPackageReq struct {
	PackageId string `json:"packageId"`
	Status    string `json:"status"`
}

type ModifyConfigReq struct {
	ConfigBase
}

type ConfigQuery struct {
	ConfigId    string `form:"configId,optional"`    // 参数主键
	TenantId    string `form:"tenantId,optional"`    // 租户编号
	ConfigName  string `form:"configName,optional"`  // 参数名称
	ConfigKey   string `form:"configKey,optional"`   // 参数键名
	ConfigValue string `form:"configValue,optional"` // 参数键值
	ConfigType  string `form:"configType,optional"`  // 系统内置（Y是 N否）
	CreateDept  int64  `form:"createDept,optional"`  // 创建部门
	CreateBy    int64  `form:"createBy,optional"`    // 创建者
	CreateTime  string `form:"createTime,optional"`  // 创建时间
	UpdateBy    int64  `form:"updateBy,optional"`    // 更新者
	UpdateTime  string `form:"updateTime,optional"`  // 更新时间
	Remark      string `form:"remark,optional"`      // 备注
}

type PageSetConfigReq struct {
	PageReq
	ConfigQuery
}

type PageSetConfigResp struct {
	Total int64         `json:"total"`
	Rows  []*ConfigBase `json:"rows"`
}

type ConfigKeyResp struct {
	Data string `json:"data"`
}

type ModifyDictDataReq struct {
	DictDataBase
}

type DictDataQuery struct {
	DictCode   int64  `form:"dictCode,optional"`   // 字典编码
	TenantId   string `form:"tenantId,optional"`   // 租户编号
	DictSort   int32  `form:"dictSort,optional"`   // 字典排序
	DictLabel  string `form:"dictLabel,optional"`  // 字典标签
	DictValue  string `form:"dictValue,optional"`  // 字典键值
	DictType   string `form:"dictType,optional"`   // 字典类型
	CssClass   string `form:"cssClass,optional"`   // 样式属性（其他样式扩展）
	ListClass  string `form:"listClass,optional"`  // 表格回显样式
	IsDefault  string `form:"isDefault,optional"`  // 是否默认（Y是 N否）
	CreateDept int64  `form:"createDept,optional"` // 创建部门
	CreateBy   int64  `form:"createBy,optional"`   // 创建者
	CreateTime string `form:"createTime,optional"` // 创建时间
	UpdateBy   int64  `form:"updateBy,optional"`   // 更新者
	UpdateTime string `form:"updateTime,optional"` // 更新时间
	Remark     string `form:"remark,optional"`     // 备注
}

type PageSetDictDataReq struct {
	PageReq
	DictDataQuery
}

type PageSetDictDataResp struct {
	Total int64           `json:"total"`
	Rows  []*DictDataBase `json:"rows"`
}

type ModifyDictTypeReq struct {
	DictTypeBase
}

type DictTypeQuery struct {
	DictId     string `form:"dictId,optional"`     // 字典主键
	TenantId   string `form:"tenantId,optional"`   // 租户编号
	DictName   string `form:"dictName,optional"`   // 字典名称
	DictType   string `form:"dictType,optional"`   // 字典类型
	CreateDept int64  `form:"createDept,optional"` // 创建部门
	CreateBy   int64  `form:"createBy,optional"`   // 创建者
	CreateTime string `form:"createTime,optional"` // 创建时间
	UpdateBy   int64  `form:"updateBy,optional"`   // 更新者
	UpdateTime string `form:"updateTime,optional"` // 更新时间
	Remark     string `form:"remark,optional"`     // 备注
}

type PageSetDictTypeReq struct {
	PageReq
	DictTypeQuery
}

type PageSetDictTypeResp struct {
	Total int64           `json:"total"`
	Rows  []*DictTypeBase `json:"rows"`
}

type ModifyOssReq struct {
	OssBase
}

type OssQuery struct {
	OssId        string `form:"ossId,optional"`        // 对象存储主键
	TenantId     string `form:"tenantId,optional"`     // 租户编号
	FileName     string `form:"fileName,optional"`     // 文件名
	OriginalName string `form:"originalName,optional"` // 原名
	FileSuffix   string `form:"fileSuffix,optional"`   // 文件后缀名
	Url          string `form:"url,optional"`          // URL地址
	Ext1         string `form:"ext1,optional"`         // 扩展字段
	CreateDept   int64  `form:"createDept,optional"`   // 创建部门
	CreateTime   string `form:"createTime,optional"`   // 创建时间
	CreateBy     int64  `form:"createBy,optional"`     // 上传人
	UpdateTime   string `form:"updateTime,optional"`   // 更新时间
	UpdateBy     int64  `form:"updateBy,optional"`     // 更新人
	Service      string `form:"service,optional"`      // 服务商
}

type PageSetOssReq struct {
	PageReq
	OssQuery
}

type PageSetOssResp struct {
	Rows  []*OssBase `json:"rows"`
	Total int64      `json:"total"`
}

type ModifyOssConfigReq struct {
	OssConfigBase
}

type OssConfigQuery struct {
	OssConfigID  string `form:"ossConfigId,optional"`  // 主键
	TenantId     string `form:"tenantId,optional"`     // 租户编号
	ConfigKey    string `form:"configKey,optional"`    // 配置key
	AccessKey    string `form:"accessKey,optional"`    // accessKey
	SecretKey    string `form:"secretKey,optional"`    // 秘钥
	BucketName   string `form:"bucketName,optional"`   // 桶名称
	Prefix       string `form:"prefix,optional"`       // 前缀
	Endpoint     string `form:"endpoint,optional"`     // 访问站点
	Domain       string `form:"domain,optional"`       // 自定义域名
	IsHTTPS      string `form:"isHttps,optional"`      // 是否https（Y=是,N=否）
	Region       string `form:"region,optional"`       // 域
	AccessPolicy string `form:"accessPolicy,optional"` // 桶权限类型(0=private 1=public 2=custom)
	Status       string `form:"status,optional"`       // 是否默认（0=是,1=否）
	Ext1         string `form:"ext1,optional"`         // 扩展字段
	CreateDept   int64  `form:"createDept,optional"`   // 创建部门
	CreateBy     int64  `form:"createBy,optional"`     // 创建者
	CreateTime   string `form:"createTime,optional"`   // 创建时间
	UpdateBy     int64  `form:"updateBy,optional"`     // 更新者
	UpdateTime   string `form:"updateTime,optional"`   // 更新时间
	Remark       string `form:"remark,optional"`       // 备注
}

type PageSetOssConfigReq struct {
	PageReq
	OssConfigQuery
}

type PageSetOssConfigResp struct {
	Rows  []*OssConfigBase `json:"rows"`
	Total int64            `json:"total"`
}

type ChangeStatusOssConfigReq struct {
	OssConfigId string `json:"ossConfigId"`
	ConfigKey   string `json:"configKey"`
	Status      string `json:"status"`
}

type OnlineInfo struct {
	Browser       string `json:"browser,optional"`       // 浏览器类型
	ClientKey     string `json:"clientKey,optional"`     // 客户端
	DeptName      string `json:"deptName,optional"`      // 部门名称
	DeviceType    string `json:"deviceType,optional"`    // 设备类型
	Ipaddr        string `json:"ipaddr,optional"`        // 登录IP地址
	LoginLocation string `json:"loginLocation,optional"` // 登录地点
	LoginTime     string `json:"loginTime,optional"`     // 访问时间
	Os            string `json:"os,optional"`            // 操作系统
	Token         string `json:"tokenId,optional"`       // Token
	UserName      string `json:"userName,optional"`      // 用户账号
}

type OnlineQuery struct {
	Ipaddr   string `json:"ipaddr,optional"`
	UserName string `json:"userName,optional"`
}

type PageSetOnlineResp struct {
	Rows  []*OnlineInfo `json:"rows"`
	Total int64         `json:"total"`
}

type OperLogQuery struct {
	OperId        string `form:"operId,optional"`        // 日志主键
	TenantId      string `form:"tenantId,optional"`      // 租户编号
	Title         string `form:"title,optional"`         // 模块标题
	BusinessType  int32  `form:"businessType,optional"`  // 业务类型（0其它 1新增 2修改 3删除）
	Method        string `form:"method,optional"`        // 方法名称
	RequestMethod string `form:"requestMethod,optional"` // 请求方式
	OperatorType  int32  `form:"operatorType,optional"`  // 操作类别（0其它 1后台用户 2手机端用户）
	OperName      string `form:"operName,optional"`      // 操作人员
	DeptName      string `form:"deptName,optional"`      // 部门名称
	OperUrl       string `form:"operUrl,optional"`       // 请求URL
	OperIp        string `form:"operIp,optional"`        // 主机地址
	OperLocation  string `form:"operLocation,optional"`  // 操作地点
	OperParam     string `form:"operParam,optional"`     // 请求参数
	JsonResult    string `form:"jsonResult,optional"`    // 返回参数
	Status        int32  `form:"status,optional"`        // 操作状态（0正常 1异常）
	ErrorMsg      string `form:"errorMsg,optional"`      // 错误消息
	OperTime      string `form:"operTime,optional"`      // 操作时间
	CostTime      int64  `form:"costTime,optional"`      // 消耗时间
}

type PageSetOperLogReq struct {
	PageReq
	OperLogQuery
}

type PageSetOperLogResp struct {
	Rows  []*OperLogBase `json:"rows"`
	Total int64          `json:"total"`
}

type LogininforQuery struct {
	InfoId        string `form:"infoId,optional"`        // 访问ID
	TenantId      string `form:"tenantId,optional"`      // 租户编号
	UserName      string `form:"userName,optional"`      // 用户账号
	ClientKey     string `form:"clientKey,optional"`     // 客户端
	DeviceType    string `form:"deviceType,optional"`    // 设备类型
	Ipaddr        string `form:"ipaddr,optional"`        // 登录IP地址
	LoginLocation string `form:"loginLocation,optional"` // 登录地点
	Browser       string `form:"browser,optional"`       // 浏览器类型
	Os            string `form:"os,optional"`            // 操作系统
	Status        string `form:"status,optional"`        // 登录状态（0成功 1失败）
	Msg           string `form:"msg,optional"`           // 提示消息
	LoginTime     string `form:"loginTime,optional"`     // 访问时间
}

type PageSetLogininforReq struct {
	PageReq
	LogininforQuery
}

type PageSetLogininforResp struct {
	Rows  []*LogininforBase `json:"rows"`
	Total int64             `json:"total"`
}

type RedisMonitorResp struct {
	Info         map[string]string `json:"info"`
	DbSize       int64             `json:"dbSize"`
	CommandStats []CommandState    `json:"commandStats"`
}

type CommandState struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type SseUserInfo struct {
	UserId   string `json:"userId"`
	UserName string `json:"userName"`
	NickName string `json:"nickName"`
	DeptName string `json:"deptName"`
}

type SseSendReq struct {
	UserId  string `path:"id,optional"`
	Message string `form:"message"`
}

type EncryptDemoResp struct {
	Plain   string `json:"plain"`
	Message string `json:"message"`
}

type MemberUserQuery struct {
	Keyword    string `form:"keyword,optional"`    // 用户名/手机号/用户ID
	AuthStatus string `form:"authStatus,optional"` // 认证状态 verification_status
	Deleted    string `form:"deleted,optional"`    // 0 正常 / 1 已删（fb_users.flag）
}

type PageSetMemberUserReq struct {
	PageReq
	MemberUserQuery
}

type MemberUserItem struct {
	Id                   string  `json:"id"`
	Username             string  `json:"username"`
	RealName             string  `json:"realName,optional"`
	IdCard               string  `json:"idCard,optional"`
	AgentLevel           int64   `json:"agentLevel,optional"` // fb_users.agent_level
	InviteCode           string  `json:"inviteCode,optional"`
	CommissionRate       float64 `json:"commissionRate,optional"`
	TotalCommission      float64 `json:"totalCommission,optional"`
	TotalBalance         float64 `json:"totalBalance,optional"`         // SUM(USD wallet balance>0)
	FundPositionAmount   float64 `json:"fundPositionAmount,optional"`   // PENDING 投信本金
	FundPositionDividend float64 `json:"fundPositionDividend,optional"` // fb_fund_profit_log.status=1
	Status               string  `json:"status,optional"`               // ACTIVE 等
	OnlineStatus         int64   `json:"onlineStatus,optional"`         // Redis online:user 或 presence 5 分钟
	LastLogin            string  `json:"lastLogin,optional"`
	CreatedAt            string  `json:"createdAt,optional"` // 注册时间
}

type PageSetMemberUserResp struct {
	Rows  []*MemberUserItem `json:"rows"`
	Total int64             `json:"total"`
}

type MemberUserStatsResp struct {
	TotalOnlineUsers    int64 `json:"totalOnlineUsers"`    // KEYS online:user:*
	TodayLogins         int64 `json:"todayLogins"`         // SCARD login:today
	TotalActiveSessions int64 `json:"totalActiveSessions"` // ZSET fb:presence:active 近 5 分钟
}

type MemberUserResetPwdReq struct {
	Id       string `json:"id"`            // fb_users.id
	Password string `json:"password"`      // 新密码；空则默认 123456
	Type     int64  `json:"type,optional"` // 1=登录密码 2=交易密码，默认 1
}

type MemberUserParentBrief struct {
	Id       string `json:"id"`
	Username string `json:"username,optional"`
	RealName string `json:"realName,optional"`
}

type MemberUserInfoResp struct {
	Id                     string                 `json:"id"`
	Username               string                 `json:"username"`
	Email                  string                 `json:"email,optional"`
	Mobile                 string                 `json:"mobile,optional"`
	Phone                  string                 `json:"phone,optional"`
	RealName               string                 `json:"realName,optional"`
	IdCard                 string                 `json:"idCard,optional"`
	VerificationStatus     string                 `json:"verificationStatus,optional"`
	Verified               bool                   `json:"verified,optional"`
	CreditScore            int64                  `json:"creditScore,optional"`
	SecurityQuestion       string                 `json:"securityQuestion,optional"`
	SecurityAnswer         string                 `json:"securityAnswer,optional"`
	Role                   string                 `json:"role,optional"`
	AccountLocked          bool                   `json:"accountLocked,optional"`
	FailedAttempts         int64                  `json:"failedAttempts,optional"`
	LastLogin              string                 `json:"lastLogin,optional"`
	ParentId               string                 `json:"parentId,optional"`
	Parent                 *MemberUserParentBrief `json:"parent,optional"`
	Level                  int64                  `json:"level,optional"`
	AgentLevel             int64                  `json:"agentLevel,optional"`
	InviteCode             string                 `json:"inviteCode,optional"`
	CommissionRate         float64                `json:"commissionRate,optional"`
	TotalCommission        float64                `json:"totalCommission,optional"`
	TeamSize               int64                  `json:"teamSize,optional"`
	Status                 string                 `json:"status,optional"`
	ContractControl        int64                  `json:"contractControl,optional"`
	IsOnline               string                 `json:"isOnline,optional"`
	Remark                 string                 `json:"remark,optional"`
	Flag                   int64                  `json:"flag,optional"`
	IsTest                 bool                   `json:"isTest,optional"`
	HasPassword            bool                   `json:"hasPassword,optional"`
	HasPayPassword         bool                   `json:"hasPayPassword,optional"`
	PayPasswordUpdatedAt   string                 `json:"payPasswordUpdatedAt,optional"`
	PayPasswordErrorCount  int64                  `json:"payPasswordErrorCount,optional"`
	PayPasswordLockedUntil string                 `json:"payPasswordLockedUntil,optional"`
	Avatar                 string                 `json:"avatar,optional"`
	TotalBalance           float64                `json:"totalBalance,optional"`
	FundPositionAmount     float64                `json:"fundPositionAmount,optional"`
	FundPositionDividend   float64                `json:"fundPositionDividend,optional"`
	OnlineStatus           int64                  `json:"onlineStatus,optional"`
	CreatedAt              string                 `json:"createdAt,optional"`
	UpdatedAt              string                 `json:"updatedAt,optional"`
}

type MemberUserUpdateReq struct {
	Id                 string  `json:"id"`
	Username           string  `json:"username,optional"`
	Password           string  `json:"password,optional"`
	PayPassword        string  `json:"payPassword,optional"`
	RealName           string  `json:"realName,optional"`
	Mobile             string  `json:"mobile,optional"`
	Email              string  `json:"email,optional"`
	IdCard             string  `json:"idCard,optional"`
	SecurityQuestion   string  `json:"securityQuestion,optional"`
	SecurityAnswer     string  `json:"securityAnswer,optional"`
	ParentId           string  `json:"parentId,optional"`
	InviteCode         string  `json:"inviteCode,optional"`
	CommissionRate     float64 `json:"commissionRate,optional"`
	TotalCommission    float64 `json:"totalCommission,optional"`
	CreditScore        int64   `json:"creditScore,optional"`
	VerificationStatus string  `json:"verificationStatus,optional"`
	AccountLocked      bool    `json:"accountLocked,optional"`
	Status             string  `json:"status,optional"`
	Verified           bool    `json:"verified,optional"`
	ContractControl    int64   `json:"contractControl,optional"`
	Remark             string  `json:"remark,optional"`
	Avatar             string  `json:"avatar,optional"`
}

type MemberKycQuery struct {
	Keyword    string `form:"keyword,optional"`    // 用户名/手机号/姓名/身份证号模糊
	AuthStatus string `form:"authStatus,optional"` // 认证状态，映射 v.status
	IdCardNo   string `form:"idCardNo,optional"`   // 身份证号精确匹配
	Username   string `form:"username,optional"`   // 用户名模糊
	RealName   string `form:"realName,optional"`   // 实名表 v.real_name 模糊
}

type PageSetMemberKycReq struct {
	PageReq
	MemberKycQuery
}

type MemberKycItem struct {
	Id           string `json:"id"`
	UserId       string `json:"userId"`
	Username     string `json:"username,optional"`
	Mobile       string `json:"mobile,optional"`
	RealName     string `json:"realName,optional"`
	IdCardNo     string `json:"idCardNo,optional"`
	IdCardFront  string `json:"idCardFront,optional"` // 证件正面 URL
	IdCardBack   string `json:"idCardBack,optional"`  // 证件反面 URL
	Status       string `json:"status,optional"`      // VERIFIED / PENDING / REJECTED
	RejectReason string `json:"rejectReason,optional"`
	VerifiedAt   string `json:"verifiedAt,optional"` // 认证通过时间
	CreatedAt    string `json:"createdAt,optional"`  // 提交时间
	UpdatedAt    string `json:"updatedAt,optional"`
}

type PageSetMemberKycResp struct {
	Rows  []*MemberKycItem `json:"rows"`
	Total int64            `json:"total"`
}

type MemberWalletQuery struct {
	Keyword      string `form:"keyword,optional"`      // 用户名/手机号/真实姓名模糊
	UserId       string `form:"userId,optional"`       // w.user_id 精确
	AccountType  string `form:"accountType,optional"`  // 对应 Java type → w.account_type
	Status       string `form:"status,optional"`       // u.status
	Verified     string `form:"verified,optional"`     // u.verified
	Username     string `form:"username,optional"`     // u.username LIKE
	Mobile       string `form:"mobile,optional"`       // u.mobile LIKE
	RealName     string `form:"realName,optional"`     // u.real_name LIKE
	Currency     string `form:"currency,optional"`     // 扩展：w.currency
	FrozenStatus string `form:"frozenStatus,optional"` // 扩展：w.frozen
}

type PageSetMemberWalletReq struct {
	PageReq
	MemberWalletQuery
}

type MemberWalletItem struct {
	Id           string  `json:"id"`
	UserId       string  `json:"userId"`
	Username     string  `json:"username,optional"`
	Mobile       string  `json:"mobile,optional"`
	RealName     string  `json:"realName,optional"`
	AccountType  string  `json:"accountType,optional"`
	Balance      float64 `json:"balance,optional"`
	FrozenAmount float64 `json:"frozenAmount,optional"`
	Frozen       bool    `json:"frozen,optional"`
	Version      string  `json:"version,optional"` // 乐观锁版本
	Currency     string  `json:"currency,optional"`
	DrawTicket   int64   `json:"drawTicket,optional"` // 抽奖券数量
	CreatedAt    string  `json:"createdAt,optional"`
	UpdatedAt    string  `json:"updatedAt,optional"`
}

type PageSetMemberWalletResp struct {
	Rows  []*MemberWalletItem `json:"rows"`
	Total int64               `json:"total"`
}

type MemberWalletAddOrSubtractReq struct {
	Id       string  `json:"id"`                // 钱包 id（fb_user_wallets.id）
	Type     bool    `json:"type"`              // true=加款，false=减款
	Amount   float64 `json:"amount"`            // 金额（正数，服务端取绝对值）
	Remark   string  `json:"remark,optional"`   // 备注；空则默认「后台调整加/减款」
	FlowType string  `json:"flowType,optional"` // ADD_AMOUNT/ADD_BONUS/ADD_DIVIDEND/ADD_TRANSFER 或 SUBTRACT_AMOUNT/ADD_TRANSFER
}

type MemberReportQuery struct {
	Keyword    string `form:"keyword,optional"`    // 用户名/手机号/真实姓名精确匹配
	Username   string `form:"username,optional"`   // 预留（Java wrapper 已注释）
	Level      string `form:"level,optional"`      // fb_users.level
	Status     string `form:"status,optional"`     // fb_users.status
	Verified   string `form:"verified,optional"`   // fb_users.verified
	OrderField string `form:"orderField,optional"` // 排序字段：created_at/last_login/level/username
	Order      string `form:"order,optional"`      // asc/desc
}

type PageSetMemberReportReq struct {
	PageReq
	MemberReportQuery
}

type MemberReportParentUser struct {
	Id       string `json:"id"`
	Username string `json:"username"`
}

type MemberReportItem struct {
	Id             string                  `json:"id"`
	UserId         string                  `json:"userId"`
	Username       string                  `json:"username,optional"`
	Mobile         string                  `json:"mobile,optional"`
	RealName       string                  `json:"realName,optional"`
	Level          int64                   `json:"level,optional"`
	Amount         float64                 `json:"amount,optional"`         // 钱包余额汇总
	RechargeAmount float64                 `json:"rechargeAmount,optional"` // 成功充值汇总
	WithdrawAmount float64                 `json:"withdrawAmount,optional"` // 成功提现汇总
	RechargeDiff   float64                 `json:"rechargeDiff,optional"`   // 充提差
	TotalProfit    float64                 `json:"totalProfit,optional"`    // fb_profit_records 累计 SUM(amount)
	TeamCount      int64                   `json:"teamCount,optional"`      // 直属下级人数 parent_id + flag=0
	RegisterTime   string                  `json:"registerTime,optional"`
	LastLogin      string                  `json:"lastLogin,optional"`
	LoginIp        string                  `json:"loginIp,optional"` // 最近登录 IP
	ParentUser     *MemberReportParentUser `json:"parentUser,optional"`
}

type PageSetMemberReportResp struct {
	Rows  []*MemberReportItem `json:"rows"`
	Total int64               `json:"total"`
}

type MemberReportFlowQuery struct {
	Status   string `form:"status,optional"`  // f.status
	Type     string `form:"type,optional"`    // f.flow_type（Java 参数名 type）
	Keyword  string `form:"keyword,optional"` // 用户名/手机/姓名/业务单号模糊
	Username string `form:"username,optional"`
	Mobile   string `form:"mobile,optional"`
	RealName string `form:"realName,optional"`
}

type PageSetMemberReportFlowReq struct {
	PageReq
	UserId string `path:"userId"`
	MemberReportFlowQuery
}

type MemberReportFlowItem struct {
	Id           string  `json:"id"`
	UserId       string  `json:"userId"`
	Username     string  `json:"username,optional"`
	Mobile       string  `json:"mobile,optional"`
	RealName     string  `json:"realName,optional"`
	AccountType  string  `json:"accountType,optional"`
	FlowType     string  `json:"flowType,optional"` // CONTRACT_BUY 等
	BeforeAmount float64 `json:"beforeAmount,optional"`
	FlowAmount   float64 `json:"flowAmount,optional"`
	AfterAmount  float64 `json:"afterAmount,optional"`
	BusinessNo   string  `json:"businessNo,optional"`
	Remark       string  `json:"remark,optional"`
	CreatedAt    string  `json:"createdAt,optional"`
	WalletId     string  `json:"walletId,optional"`
	Currency     string  `json:"currency,optional"`
	Description  string  `json:"description,optional"`
	Status       string  `json:"status,optional"` // SUCCESS 等
	UpdatedAt    string  `json:"updatedAt,optional"`
}

type PageSetMemberReportFlowResp struct {
	Rows  []*MemberReportFlowItem `json:"rows"`
	Total int64                   `json:"total"`
}

type MemberTeamQuery struct {
	Keyword string `form:"keyword,optional"` // 用户名/手机号/身份证/姓名；stats 模糊 LIMIT 1
	Status  string `form:"status,optional"`  // fb_users.status（仅 GET /list）
}

type PageSetMemberTeamReq struct {
	PageReq
	MemberTeamQuery
}

type MemberTeamAgent struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	RealName string `json:"realName,optional"`
}

type MemberTeamStatsResp struct {
	TotalMembers     int64   `json:"totalMembers"`
	Level1Members    int64   `json:"level1Members"` // 一级下级数（全局时为顶层用户数）
	Level2Members    int64   `json:"level2Members"`
	Level3Members    int64   `json:"level3Members"`
	Level4Members    int64   `json:"level4Members"`
	Level5Members    int64   `json:"level5Members"`
	TotalTeamBalance float64 `json:"totalTeamBalance"` // 全库或根用户下级钱包余额总和
}

type MemberTeamItem struct {
	Id               string           `json:"id"`
	Username         string           `json:"username,optional"`
	Agent            *MemberTeamAgent `json:"agent,optional"`
	RealName         string           `json:"realName,optional"`
	Level            int64            `json:"level,optional"`
	Status           string           `json:"status,optional"`
	TeamSize         int64            `json:"teamSize,optional"`      // fb_users.team_size
	Level1Members    int64            `json:"level1Members,optional"` // 直属下级数
	Level2Members    int64            `json:"level2Members,optional"`
	Level3Members    int64            `json:"level3Members,optional"`
	Level4Members    int64            `json:"level4Members,optional"`
	Level5Members    int64            `json:"level5Members,optional"`
	AgentLevel       int64            `json:"agentLevel,optional"`
	WalletCount      int64            `json:"walletCount,optional"`
	Balance          float64          `json:"balance,optional"`          // 个人钱包余额
	TotalTeamBalance float64          `json:"totalTeamBalance,optional"` // 下级团队余额（预留）
	CreatedAt        string           `json:"createdAt,optional"`
}

type PageSetMemberTeamResp struct {
	Rows  []*MemberTeamItem `json:"rows"`
	Total int64             `json:"total"`
}

type MemberTeamDetailResp struct {
	Id            string  `json:"id"`
	Username      string  `json:"username,optional"`
	AgentLevel    int64   `json:"agentLevel,optional"`
	WalletCount   int64   `json:"walletCount,optional"`
	TotalAssets   float64 `json:"totalAssets,optional"`
	TotalDeposit  float64 `json:"totalDeposit,optional"`
	TotalWithdraw float64 `json:"totalWithdraw,optional"`
	CreatedAt     string  `json:"createdAt,optional"`
}

type MemberTeamMemberItem struct {
	Level         int64   `json:"level,optional"`
	Username      string  `json:"username,optional"`
	TotalAssets   float64 `json:"totalAssets,optional"`
	TotalDeposit  float64 `json:"totalDeposit,optional"`
	TotalInvest   float64 `json:"totalInvest,optional"`
	TotalWithdraw float64 `json:"totalWithdraw,optional"`
}

type PageSetMemberTeamMembersReq struct {
	PageReq
	UserId string `path:"userId"`
}

type PageSetMemberTeamMembersResp struct {
	Rows  []*MemberTeamMemberItem `json:"rows"`
	Total int64                   `json:"total"`
}

type MemberTeamChangeParentReq struct {
	UserId   string `json:"userId"`   // 被操作用户 fb_users.id
	Username string `json:"username"` // 新上级用户名（必填）；对齐 Java AgentChangeRequest
}

type MemberTeamChangeParentResp struct {
	UserId         string `json:"userId"`
	ParentId       string `json:"parentId,optional"`
	ParentUsername string `json:"parentUsername,optional"`
}

type MemberTeamAgentLevelReq struct {
	UserId     string `json:"userId"`     // fb_users.id，对齐 Java AgentLevelUpdateRequest
	AgentLevel int64  `json:"agentLevel"` // 最大展开层级 3/4/5
}

type MemberTeamAgentLevelResp struct {
	UserId     string `json:"userId"`
	AgentLevel int64  `json:"agentLevel"`
}

type MemberLoginLogQuery struct {
	Keyword     string `form:"keyword,optional"`     // 用户名/姓名/设备ID/IP
	LoginResult string `form:"loginResult,optional"` // SUCCESS / FAIL
	LoginMethod string `form:"loginMethod,optional"` // 对应 fb_device_login_log.login_type
	RiskLevel   string `form:"riskLevel,optional"`   // LOW / MEDIUM / HIGH
	IpType      string `form:"ipType,optional"`      // 预留筛选
	TimeRange   string `form:"timeRange,optional"`   // 预留快捷时间
	FailReason  string `form:"failReason,optional"`
	DeviceType  string `form:"deviceType,optional"`
	Browser     string `form:"browser,optional"`
}

type PageSetMemberLoginLogReq struct {
	PageReq
	MemberLoginLogQuery
}

type MemberLoginLogItem struct {
	Id            string `json:"id"`
	UserId        string `json:"userId"`
	Username      string `json:"username,optional"`
	RealName      string `json:"realName,optional"`
	DeviceId      string `json:"deviceId,optional"`
	LoginTime     string `json:"loginTime,optional"`
	LoginIp       string `json:"loginIp,optional"`
	LoginLocation string `json:"loginLocation,optional"`
	LoginType     string `json:"loginType,optional"` // PASSWORD 等（非 loginMethod）
	LoginResult   string `json:"loginResult,optional"`
	FailReason    string `json:"failReason,optional"`
	RiskLevel     string `json:"riskLevel,optional"`
	RiskDetail    string `json:"riskDetail,optional"`
}

type PageSetMemberLoginLogResp struct {
	Rows  []*MemberLoginLogItem `json:"rows"`
	Total int64                 `json:"total"`
}

type FundWalletApplyQuery struct {
	Keyword     string `form:"keyword,optional"`     // 用户名/手机/姓名模糊
	Status      string `form:"status,optional"`      // a.status：PENDING/APPROVED/REJECTED
	State       string `form:"state,optional"`       // a.state
	Verified    string `form:"verified,optional"`    // u.verified
	UserId      string `form:"userId,optional"`      // a.user_id 精确
	Username    string `form:"username,optional"`    // u.username LIKE
	Mobile      string `form:"mobile,optional"`      // u.mobile LIKE
	RealName    string `form:"realName,optional"`    // u.real_name LIKE
	AccountType string `form:"accountType,optional"` // a.account_type（Go 扩展）
}

type PageSetFundWalletApplyReq struct {
	PageReq
	FundWalletApplyQuery
}

type FundWalletApplyItem struct {
	Id                  string `json:"id"`
	UserId              string `json:"userId"`
	Username            string `json:"username,optional"`
	Mobile              string `json:"mobile,optional"`
	RealName            string `json:"realName,optional"`
	AccountType         string `json:"accountType,optional"`
	Status              string `json:"status,optional"`
	State               string `json:"state,optional"`
	RiskAssessmentScore int64  `json:"riskAssessmentScore,optional"`
	RejectReason        string `json:"rejectReason,optional"`
	ApplyTime           string `json:"applyTime,optional"`
	AuditTime           string `json:"auditTime,optional"`
	AuditUserId         string `json:"auditUserId,optional"`
	AuditUser           string `json:"auditUser,optional"`
	Remark              string `json:"remark,optional"`
	CreatedAt           string `json:"createdAt,optional"`
	UpdatedAt           string `json:"updatedAt,optional"`
}

type PageSetFundWalletApplyResp struct {
	Rows  []*FundWalletApplyItem `json:"rows"`
	Total int64                  `json:"total"`
}

type FundWalletApplyBasicInfo struct {
	Id                  string `json:"id"`
	Username            string `json:"username,optional"`
	AccountType         string `json:"accountType,optional"`
	RiskAssessmentScore int64  `json:"riskAssessmentScore,optional"`
	Status              string `json:"status,optional"`
	ApplyTime           string `json:"applyTime,optional"`
	AuditTime           string `json:"auditTime,optional"`
	RejectReason        string `json:"rejectReason,optional"`
	Remark              string `json:"remark,optional"`
}

type FundWalletApplySecurityInfo struct {
	TwoFactorEnabled bool  `json:"twoFactorEnabled"`
	SecurityScore    int64 `json:"securityScore"`
	IdentityVerified bool  `json:"identityVerified"`
}

type FundWalletApplyLoginStats struct {
	CommonLoginIp   string `json:"commonLoginIp,optional"`
	LastLoginTime   string `json:"lastLoginTime,optional"`
	CommonLoginArea string `json:"commonLoginArea,optional"`
	MonthLoginCount int64  `json:"monthLoginCount,optional"`
}

type FundWalletApplyFlowStats struct {
	TradeSuccessRate string           `json:"tradeSuccessRate,optional"`
	MonthFlowCount   int64            `json:"monthFlowCount,optional"`
	DailyAvgAmount   float64          `json:"dailyAvgAmount,optional"`
	MonthIncome      float64          `json:"monthIncome,optional"`
	MonthExpense     float64          `json:"monthExpense,optional"`
	TypeStatsMap     map[string]int64 `json:"typeStatsMap,optional"`
}

type FundWalletApplyDetailResp struct {
	Id           string                       `json:"id,optional"`
	UserId       string                       `json:"userId,optional"`
	BasicInfo    *FundWalletApplyBasicInfo    `json:"basicInfo,optional"`
	SecurityInfo *FundWalletApplySecurityInfo `json:"securityInfo,optional"`
	LoginStats   *FundWalletApplyLoginStats   `json:"loginStats,optional"`
	FlowStats    *FundWalletApplyFlowStats    `json:"flowStats,optional"`
}

type FundWalletApplyCurrentMonthFlowReq struct {
	UserId string `form:"userId"`
}

type FundWalletApplyFlowItem struct {
	Id           string  `json:"id"`
	UserId       string  `json:"userId"`
	AccountType  string  `json:"accountType,optional"`
	FlowType     string  `json:"flowType,optional"`
	BeforeAmount float64 `json:"beforeAmount,optional"`
	FlowAmount   float64 `json:"flowAmount,optional"`
	AfterAmount  float64 `json:"afterAmount,optional"`
	BusinessNo   string  `json:"businessNo,optional"`
	Remark       string  `json:"remark,optional"`
	CreatedAt    string  `json:"createdAt,optional"`
	WalletId     string  `json:"walletId,optional"`
	Currency     string  `json:"currency,optional"`
	Description  string  `json:"description,optional"`
	Status       string  `json:"status,optional"`
	UpdatedAt    string  `json:"updatedAt,optional"`
}

type FundWalletApplyCurrentMonthFlowResp struct {
	Rows  []*FundWalletApplyFlowItem `json:"rows"`
	Total int64                      `json:"total"`
}

type FundWalletApplyLoginLogQuery struct {
	Status   string `form:"status,optional"`   // d.login_result
	Keyword  string `form:"keyword,optional"`  // 用户名/手机/姓名/IP 模糊
	Username string `form:"username,optional"` // u.username LIKE
	RealName string `form:"realName,optional"` // u.real_name LIKE
}

type PageSetFundWalletApplyLoginLogReq struct {
	PageReq
	UserId string `path:"userId"`
	FundWalletApplyLoginLogQuery
}

type FundWalletApplyLoginLogItem struct {
	Id            string `json:"id"`
	UserId        string `json:"userId"`
	Username      string `json:"username,optional"`
	LoginTime     string `json:"loginTime,optional"`
	LoginIp       string `json:"loginIp,optional"`
	LoginLocation string `json:"loginLocation,optional"`
	LoginType     string `json:"loginType,optional"`
	LoginResult   string `json:"loginResult,optional"`
	FailReason    string `json:"failReason,optional"`
	RiskLevel     string `json:"riskLevel,optional"`
	RiskDetail    string `json:"riskDetail,optional"`
}

type PageSetFundWalletApplyLoginLogResp struct {
	Rows  []*FundWalletApplyLoginLogItem `json:"rows"`
	Total int64                          `json:"total"`
}

type FundStatementQuery struct {
	Keyword  string `form:"keyword,optional"`  // 用户名/手机/姓名/业务单号模糊
	Status   string `form:"status,optional"`   // f.status（Java 参数名 status）
	Type     string `form:"type,optional"`     // f.flow_type（Java 参数名 type）
	Currency string `form:"currency,optional"` // f.currency
	UserId   string `form:"userId,optional"`   // f.user_id 精确
	Username string `form:"username,optional"` // u.username LIKE
	Mobile   string `form:"mobile,optional"`   // u.mobile LIKE
	RealName string `form:"realName,optional"` // u.real_name LIKE
}

type PageSetFundStatementReq struct {
	PageReq
	FundStatementQuery
}

type FundStatementItem struct {
	Id           string  `json:"id"`
	UserId       string  `json:"userId"`
	Username     string  `json:"username,optional"`
	Mobile       string  `json:"mobile,optional"`
	RealName     string  `json:"realName,optional"`
	AccountType  string  `json:"accountType,optional"`
	FlowType     string  `json:"flowType,optional"`
	BeforeAmount float64 `json:"beforeAmount,optional"`
	FlowAmount   float64 `json:"flowAmount,optional"`
	AfterAmount  float64 `json:"afterAmount,optional"`
	BusinessNo   string  `json:"businessNo,optional"`
	Remark       string  `json:"remark,optional"`
	CreatedAt    string  `json:"createdAt,optional"`
	WalletId     string  `json:"walletId,optional"`
	Currency     string  `json:"currency,optional"`
	Description  string  `json:"description,optional"`
	Status       string  `json:"status,optional"`
	UpdatedAt    string  `json:"updatedAt,optional"`
}

type PageSetFundStatementResp struct {
	Rows  []*FundStatementItem `json:"rows"`
	Total int64                `json:"total"`
}

type FundWithdrawQuery struct {
	Keyword  string `form:"keyword,optional"`  // 用户名/手机/姓名/订单号模糊
	Status   string `form:"status,optional"`   // w.status
	Type     string `form:"type,optional"`     // w.withdraw_type（Java 参数名 type）
	Username string `form:"username,optional"` // u.username LIKE
	Mobile   string `form:"mobile,optional"`   // u.mobile LIKE
	RealName string `form:"realName,optional"` // u.real_name LIKE
}

type PageSetFundWithdrawReq struct {
	PageReq
	FundWithdrawQuery
}

type FundWithdrawItem struct {
	Id            string  `json:"id"`
	UserId        string  `json:"userId"`
	Username      string  `json:"username,optional"`
	Mobile        string  `json:"mobile,optional"`
	RealName      string  `json:"realName,optional"`
	OrderNo       string  `json:"orderNo,optional"`
	Amount        float64 `json:"amount,optional"`
	Status        string  `json:"status,optional"`
	WithdrawType  string  `json:"withdrawType,optional"`
	BankName      string  `json:"bankName,optional"`
	BankCardNo    string  `json:"bankCardNo,optional"`
	AccountName   string  `json:"accountName,optional"`
	PaymentStatus string  `json:"paymentStatus,optional"`
	PaymentNo     string  `json:"paymentNo,optional"`
	PaymentTime   string  `json:"paymentTime,optional"`
	Remark        string  `json:"remark,optional"`
	RejectReason  string  `json:"rejectReason,optional"`
	CreatedAt     string  `json:"createdAt,optional"`
	UpdatedAt     string  `json:"updatedAt,optional"`
}

type PageSetFundWithdrawResp struct {
	Rows  []*FundWithdrawItem `json:"rows"`
	Total int64               `json:"total"`
}

type FundWithdrawRejectReq struct {
	Id     string `json:"id"`
	Remark string `json:"remark"`
}

type FundRechargeQuery struct {
	Keyword  string `form:"keyword,optional"`  // 用户名/手机/姓名/订单号模糊
	Status   string `form:"status,optional"`   // d.status
	Username string `form:"username,optional"` // u.username LIKE
	Mobile   string `form:"mobile,optional"`   // u.mobile LIKE
	RealName string `form:"realName,optional"` // u.real_name LIKE
}

type PageSetFundRechargeReq struct {
	PageReq
	FundRechargeQuery
}

type FundRechargeItem struct {
	Id            string  `json:"id"`
	UserId        string  `json:"userId"`
	Username      string  `json:"username,optional"`
	Mobile        string  `json:"mobile,optional"`
	RealName      string  `json:"realName,optional"`
	OrderNo       string  `json:"orderNo,optional"`
	Amount        float64 `json:"amount,optional"`
	Status        string  `json:"status,optional"`
	PaymentMethod string  `json:"paymentMethod,optional"`
	PaymentStatus string  `json:"paymentStatus,optional"`
	PaymentNo     string  `json:"paymentNo,optional"`
	PaymentTime   string  `json:"paymentTime,optional"`
	Remark        string  `json:"remark,optional"`
	Currency      string  `json:"currency,optional"`
	TargetAccount string  `json:"targetAccount,optional"`
	Screenshot    string  `json:"screenshot,optional"`
	CreatedAt     string  `json:"createdAt,optional"`
	UpdatedAt     string  `json:"updatedAt,optional"`
}

type PageSetFundRechargeResp struct {
	Rows  []*FundRechargeItem `json:"rows"`
	Total int64               `json:"total"`
}

type FundRechargeRejectReq struct {
	Id     string `json:"id"`
	Remark string `json:"remark"`
}

type TradeContractQuery struct {
	Keyword   string `form:"keyword,optional"`
	Status    string `form:"status,optional"`
	Symbol    string `form:"symbol,optional"`
	Direction string `form:"direction,optional"`
}

type PageSetTradeContractReq struct {
	PageReq
	TradeContractQuery
}

type TradeContractItem struct {
	Id            string `json:"id"`
	UserName      string `json:"userName"`
	RealName      string `json:"realName"`
	BalanceU      string `json:"balanceU"`
	Symbol        string `json:"symbol"`
	Direction     string `json:"direction"`
	TradeAmount   string `json:"tradeAmount"`
	ActualProfit  string `json:"actualProfit"`
	Status        string `json:"status"`
	DurationSec   string `json:"durationSec"`
	OpenPrice     string `json:"openPrice"`
	ClosePrice    string `json:"closePrice"`
	OrderControl  string `json:"orderControl"`
	ControlResult string `json:"controlResult"`
	GlobalControl string `json:"globalControl"`
	OpenTime      string `json:"openTime"`
	SettleTime    string `json:"settleTime"`
}

type PageSetTradeContractResp struct {
	Rows  []*TradeContractItem `json:"rows"`
	Total int64                `json:"total"`
}

type TradeEntrustQuery struct {
	Keyword     string `form:"keyword,optional"`
	OrderStatus string `form:"orderStatus,optional"`
	MarketCode  string `form:"marketCode,optional"`
}

type PageSetTradeEntrustReq struct {
	PageReq
	TradeEntrustQuery
}

type TradeEntrustItem struct {
	Id              string `json:"id"`
	OrderNo         string `json:"orderNo"`
	UserName        string `json:"userName"`
	MarketCode      string `json:"marketCode"`
	StockCode       string `json:"stockCode"`
	OrderType       string `json:"orderType"`
	EntrustPrice    string `json:"entrustPrice"`
	EntrustQty      string `json:"entrustQty"`
	DealQty         string `json:"dealQty"`
	OrderStatus     string `json:"orderStatus"`
	StopLossPrice   string `json:"stopLossPrice"`
	PriceType       string `json:"priceType"`
	PriceFloatRange string `json:"priceFloatRange"`
	Validity        string `json:"validity"`
	Fee             string `json:"fee"`
	Direction       string `json:"direction"`
	LimitPrice      string `json:"limitPrice"`
	EntrustTime     string `json:"entrustTime"`
}

type PageSetTradeEntrustResp struct {
	Rows  []*TradeEntrustItem `json:"rows"`
	Total int64               `json:"total"`
}

type TradeDealQuery struct {
	Keyword    string `form:"keyword,optional"`
	MarketCode string `form:"marketCode,optional"`
	DealType   string `form:"dealType,optional"`
}

type PageSetTradeDealReq struct {
	PageReq
	TradeDealQuery
}

type TradeDealItem struct {
	Id         string `json:"id"`
	DealNo     string `json:"dealNo"`
	UserName   string `json:"userName"`
	MarketCode string `json:"marketCode"`
	StockCode  string `json:"stockCode"`
	DealType   string `json:"dealType"`
	DealPrice  string `json:"dealPrice"`
	DealQty    string `json:"dealQty"`
	DealAmount string `json:"dealAmount"`
	Fee        string `json:"fee"`
	DealTime   string `json:"dealTime"`
}

type PageSetTradeDealResp struct {
	Rows  []*TradeDealItem `json:"rows"`
	Total int64            `json:"total"`
}

type InvestPositionQuery struct {
	Keyword        string `form:"keyword,optional"`
	InvestCode     string `form:"investCode,optional"`
	PositionStatus string `form:"positionStatus,optional"`
}

type PageSetInvestPositionReq struct {
	PageReq
	InvestPositionQuery
}

type InvestPositionItem struct {
	Id             string `json:"id"`
	UserName       string `json:"userName"`
	RealName       string `json:"realName"`
	InvestCode     string `json:"investCode"`
	PositionAmount string `json:"positionAmount"`
	BuyDate        string `json:"buyDate"`
	StartDate      string `json:"startDate"`
	EndDate        string `json:"endDate"`
	PeriodDays     string `json:"periodDays"`
	FixedYieldRate string `json:"fixedYieldRate"`
	PositionStatus string `json:"positionStatus"`
	EndStatus      string `json:"endStatus"`
	LastProfitDate string `json:"lastProfitDate"`
	CreateTime     string `json:"createTime"`
	UpdateTime     string `json:"updateTime"`
}

type PageSetInvestPositionResp struct {
	Rows  []*InvestPositionItem `json:"rows"`
	Total int64                 `json:"total"`
}

type InvestListQuery struct {
	Keyword string `form:"keyword,optional"`
	Status  string `form:"status,optional"`
	SoldOut string `form:"soldOut,optional"`
}

type PageSetInvestListReq struct {
	PageReq
	InvestListQuery
}

type InvestListItem struct {
	Id               string `json:"id"`
	InvestCode       string `json:"investCode"`
	InvestName       string `json:"investName"`
	Logo             string `json:"logo"`
	ProductDesc      string `json:"productDesc"`
	Status           string `json:"status"`
	SoldOut          string `json:"soldOut"`
	SortOrder        string `json:"sortOrder"`
	YieldDisplay     string `json:"yieldDisplay"`
	YieldRate        string `json:"yieldRate"`
	InvestableAmount string `json:"investableAmount"`
	MinAddAmount     string `json:"minAddAmount"`
	Period           string `json:"period"`
	YieldType        string `json:"yieldType"`
	ExpireDate       string `json:"expireDate"`
	CreateTime       string `json:"createTime"`
	UpdateTime       string `json:"updateTime"`
}

type PageSetInvestListResp struct {
	Rows  []*InvestListItem `json:"rows"`
	Total int64             `json:"total"`
}

type ProductConfigQuery struct {
	Keyword     string `form:"keyword,optional"`
	ProductType string `form:"productType,optional"`
	Status      string `form:"status,optional"`
}

type PageSetProductConfigReq struct {
	PageReq
	ProductConfigQuery
}

type ProductConfigItem struct {
	Id           string `json:"id"`
	ProductCode  string `json:"productCode"`
	ProductAlias string `json:"productAlias"`
	Symbol       string `json:"symbol"`
	ProductName  string `json:"productName"`
	ProductType  string `json:"productType"`
	Market       string `json:"market"`
	Odds         string `json:"odds"`
	TradeTime    string `json:"tradeTime"`
	Currencies   string `json:"currencies"`
	Status       string `json:"status"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type PageSetProductConfigResp struct {
	Rows  []*ProductConfigItem `json:"rows"`
	Total int64                `json:"total"`
}

type ProductRealtimeQuery struct {
	Keyword     string `form:"keyword,optional"`
	ProductCode string `form:"productCode,optional"`
	Type        string `form:"type,optional"`
}

type PageSetProductRealtimeReq struct {
	PageReq
	ProductRealtimeQuery
}

type ProductRealtimeItem struct {
	Id            string `json:"id"`
	ProductCode   string `json:"productCode"`
	TradeCode     string `json:"tradeCode"`
	Name          string `json:"name"`
	Type          string `json:"type"`
	CurrentPrice  string `json:"currentPrice"`
	ChangeAmount  string `json:"changeAmount"`
	ChangePercent string `json:"changePercent"`
	OpenPrice     string `json:"openPrice"`
	HighPrice     string `json:"highPrice"`
	LowPrice      string `json:"lowPrice"`
	Volume        string `json:"volume"`
	Turnover      string `json:"turnover"`
	Direction     string `json:"direction"`
	TradeDate     string `json:"tradeDate"`
	UpdateTime    string `json:"updateTime"`
}

type PageSetProductRealtimeResp struct {
	Rows  []*ProductRealtimeItem `json:"rows"`
	Total int64                  `json:"total"`
}

type ProductHistoryQuery struct {
	Keyword     string `form:"keyword,optional"`
	ProductCode string `form:"productCode,optional"`
	Market      string `form:"market,optional"`
}

type PageSetProductHistoryReq struct {
	PageReq
	ProductHistoryQuery
}

type ProductHistoryItem struct {
	Id            string `json:"id"`
	ProductCode   string `json:"productCode"`
	ProductName   string `json:"productName"`
	ProductType   string `json:"productType"`
	Market        string `json:"market"`
	TradeDate     string `json:"tradeDate"`
	OpenPrice     string `json:"openPrice"`
	HighPrice     string `json:"highPrice"`
	LowPrice      string `json:"lowPrice"`
	ClosePrice    string `json:"closePrice"`
	ChangeAmount  string `json:"changeAmount"`
	ChangePercent string `json:"changePercent"`
	Volume        string `json:"volume"`
	Turnover      string `json:"turnover"`
	UpdateTime    string `json:"updateTime"`
}

type PageSetProductHistoryResp struct {
	Rows  []*ProductHistoryItem `json:"rows"`
	Total int64                 `json:"total"`
}

type NotifyNewsQuery struct {
	Keyword string `form:"keyword,optional"`
	Source  string `form:"source,optional"`
}

type PageSetNotifyNewsReq struct {
	PageReq
	NotifyNewsQuery
}

type NotifyNewsItem struct {
	Id          string `json:"id"`
	Title       string `json:"title"`
	Summary     string `json:"summary"`
	Content     string `json:"content"`
	Source      string `json:"source"`
	Link        string `json:"link"`
	Image       string `json:"image"`
	ViewCount   string `json:"viewCount"`
	PublishTime string `json:"publishTime"`
}

type PageSetNotifyNewsResp struct {
	Rows  []*NotifyNewsItem `json:"rows"`
	Total int64             `json:"total"`
}

type NotifyPublishQuery struct {
	Keyword    string `form:"keyword,optional"`
	NotifyType string `form:"notifyType,optional"`
	ReadStatus string `form:"readStatus,optional"`
}

type PageSetNotifyPublishReq struct {
	PageReq
	NotifyPublishQuery
}

type NotifyPublishItem struct {
	Id            string `json:"id"`
	ReceiveUserId string `json:"receiveUserId"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	NotifyType    string `json:"notifyType"`
	ReadStatus    string `json:"readStatus"`
	Deleted       string `json:"deleted"`
	SendTime      string `json:"sendTime"`
	ExpireTime    string `json:"expireTime"`
}

type PageSetNotifyPublishResp struct {
	Rows  []*NotifyPublishItem `json:"rows"`
	Total int64                `json:"total"`
}

type KlineMainQuery struct {
	Keyword     string `form:"keyword,optional"`
	ProductCode string `form:"productCode,optional"`
	Symbol      string `form:"symbol,optional"`
}

type PageSetKlineMainReq struct {
	PageReq
	KlineMainQuery
}

type KlineMainItem struct {
	Id          string `json:"id"`
	ProductCode string `json:"productCode"`
	Symbol      string `json:"symbol"`
	RedisKey    string `json:"redisKey"`
	BarCount    string `json:"barCount"`
	LatestTime  string `json:"latestTime"`
	Open        string `json:"open"`
	High        string `json:"high"`
	Low         string `json:"low"`
	Close       string `json:"close"`
	Volume      string `json:"volume"`
}

type PageSetKlineMainResp struct {
	Rows  []*KlineMainItem `json:"rows"`
	Total int64            `json:"total"`
}
